### ISSUE TITLE
Virtual Crates

### ISSUE THREAD

**Issue by jakcameron** [Hazebyte/CrateReloaded#1]
So Virtual Crates, where you define in the config where you want the crate to be in a gui with a size of the gui, you will set the crate on a block as ./cr setvirtualcrate this will set a virtual crate when you punch the items it will come up as the same menu one will be where you can open the keys and another where you can see the items in the keys (Left click and right click on the crate)

Config:

VirtualCrates:
  Default_Item: Stained_Pane_Glass (This will be if no item is found on the crates)
  ItemShowTitle: "&cClick to see whats inside a crate" (This will be the title of the gui on punch of the crate)
  ItemTitle: "&cClick to enter a crate" (This will be the title of the gui on right click)
  Rows: 3
  Crates:
    Vote:
      Slot: 9
      Item: Diamond (This will be the item of the crate)
      Name: "&aVote Crate"
      Lore:
       - "&7Amount&8 &e%amount%"
Command:
  /Crate givevkey name crate amount
  /Crate giveallvkey name crate amount
Alias: V, Virtual

**Comment by iAmWillX** [comment]
Split into three issues. Check #2, #3.
