### ISSUE TITLE
Reward immediately if a crate animation is active while the server restarts.

### ISSUE THREAD

**Issue by mibby** [Hazebyte/CrateReloaded#112]
Would it be possible to reward immediately if someone is using a CSGO roulette crate and it is still in the animation pending giving out the reward while the server is automatically restarting?

**Comment by imWillX** [comment]
Yes, definitely. This is a perfect time i'm reworking the code.

**Comment by imWillX** [comment]
Setting up claims for offline player inventory handling. 

For:
Give Commands
Crates that don't have instant rewards

**Comment by imWillX** [comment]
Add support for a claim system. Testing via private builds.

'/cr claim'
