### ISSUE TITLE
Documentation should be updated

### ISSUE THREAD

**Issue by Plajer** [Hazebyte/CrateReloaded#118]
I think that plugin's documentation (http://crate.hazebyte.com/guide/pro/user/start-guide/) is outdated. I didn't find any information about:
- holograpics
- onetime in reward section
- rows in preview

There can be more things of course. I find that features on github issues :o
Footer is outdated to:
`Copyright (C) 2015-2016, Hazebyte.`

**Comment by imWillX** [comment]
Hiya,

Thanks for the notice. We're currently renovating features of the plugin. Once finalized changes, i'll be updating the documentation.

**Comment by Plajer** [comment]
Any news about update? :)

**Comment by imWillX** [comment]
https://github.com/Hazebyte/Documentation

https://hazebyte.github.io/Documentation/

**Comment by imWillX** [comment]
Closing: https://hazebyte.github.io/CrateReloaded/#/
