### ISSUE TITLE
Crates like Districtpvp 

### ISSUE THREAD

**Issue by lenbey** [Hazebyte/CrateReloaded#123]
Basically you place down a chest it "drops" a few items and after that it disappears

**Comment by imWillX** [comment]
Do you have anything for reference? A GIF, video, etc?

**Comment by lenbey** [comment]
uploading it to youtube right now

**Comment by lenbey** [comment]
https://www.youtube.com/watch?v=sGrSzSHFseM&feature=youtu.be

**Comment by ProfCube** [comment]
@lenbey That looks really cool ❤ hopefully @imWillX adds this feature :D
