### ISSUE TITLE
Request: Simple mob to drop keys when mining

### ISSUE THREAD

**Issue by TheZenKitteh** [Hazebyte/CrateReloaded#136]
It would be cool if there could be a simple mob that spawns randomly when mining blocks that when killed will have a chance of dropping a certain key. For example maybe one key has a 90% change of dropping while another key has 5% and another two keys have 2.5%. So when a player is mining and the mob spawns from the block, when killed, there is a chance to get one of the keys.

The mob could be as simple as an animated stone or an animated version of the texture of the block that was broken. The chances of a block spawning the mob needs to be configurable. The drops need to be confirguable as well, but only keys. The chances of each drop also needs to be configurable.

I'm making this suggestion because I just spent a few hours trying to find a bukkit plugin that will do this and I can't find anything. I want players on my server to be able to obtain crate keys while mining to encourage mining. I have four different crates so four different keys and one is common and one is very rare while the other two are somewhere in between.

**Comment by imWillX** [comment]
Hey there,

This sounds like a whole new plugin. If your interested in building a plugin to do this, i'll be willing to setup an API for you!
