### ISSUE TITLE
Quickshop Compatibilty

### ISSUE THREAD

**Issue by imWillX** [Hazebyte/CrateReloaded#137]

**Comment by jordanwilliams1** [comment]
Can we please add this? I Bought this crate plugin and assumed it would work with quick shop 😢

**Comment by imWillX** [comment]
@jordanwilliams1 I'll take a look by next week.

**Comment by jordanwilliams1** [comment]
Thanks 😄

**Comment by imWillX** [comment]
Hello @jordanwilliams1 
Currently checking out quickshop. It seems that they use right click to setup a shop however our right click function is dedicated to opening a key. It would be much better for quickshop to add in support for CrateReloaded interact events.

An API is on the works.
