### ISSUE TITLE
Random amount changes while the server is running

### ISSUE THREAD

**Issue by L4BORG** [Hazebyte/CrateReloaded#148]
Some times the value in the GUI changes (rewards as well) on it's own and it shows other amounts, for example 64 diamond blocks would turn to 18 diamond blocks (random numbers from what I saw so far) etc, this is bugging for quite awhile now, restart or /cr reload would fix the issue... but that's not really "fix" as we can not restart servers every hour or so.

This issue is present on latest CR (from spigotmc), we're running latest paper spigot 1.8.8.

**Comment by imWillX** [comment]
We'll try to implement a solution where we clone the itemstack before displaying it in the preview menu and giving it to the player.

**Comment by imWillX** [comment]
Closing as 2.0-alpha is released. If the issue still occurs, please reopen the issue.
