### ISSUE TITLE
Offline Rewarding

### ISSUE THREAD

**Issue by mibby** [Hazebyte/CrateReloaded#157]
Would it be possible to provide keys to offline players and allow them to redeem / claim the keys stored for when they next get online? This would allow players to purchase keys from a site store without requiring them to be online, as well as allow rewarding players keys for voting without requiring them to be online.

**Comment by imWillX** [comment]
todo: 

Claim Command

**Comment by mibby** [comment]
Can't wait until this is something finally supported and available! Would also help with rewarding players keys in worlds that have separate inventories like arenas so they only redeem in the main world. :)

**Comment by imWillX** [comment]
Add support for offline key giving. 

'/cr claim'
