### ISSUE TITLE
Citizens issue with CrateReloaded

### ISSUE THREAD

**Issue by SynxPlays** [Hazebyte/CrateReloaded#162]
Hello,
I would like to report a bug with NPC GUI, where you can preview crates and (Right-Click) on NPC and open it. Everything seems okey, but that moment when I write /citizens reload, it brokes and doesn't work. It only works, when I restart my server.

Thank you.

**Comment by imWillX** [comment]
Notes: NPC support may be implemented in an open source project. 

Using API: https://github.com/Hazebyte/CrateReloadedAPI

**Comment by imWillX** [comment]
Likely to be fixed.

If there are any more issues, report them here. https://github.com/Hazebyte/CrateReloadedNPC
