### ISSUE TITLE
New crate types.

### ISSUE THREAD

**Issue by mibby** [Hazebyte/CrateReloaded#163]
Discovered this plugin and noticed it has a handful of unique crate types not in CrateReloaded. Perhaps some of them could be added in the future?

https://www.spigotmc.org/resources/crazy-crates-now-with-10-different-crate-types.17599/

**Comment by imWillX** [comment]
Hey @mibby,

Sure thing, I'll implement one new animation or crate type this week. Which one are you most interested in?

**Comment by mibby** [comment]
They all seem kind of crazy and fun so it would be nice to have a similar crate type variety in CrateReloaded eventually. Wheel, wonder, and cosmic seem the most immediately different but whatever you personally feel like working on is fine to me.

The plugin does seem to be open source too so you could take a glance and get a general idea for how it functions.

**Comment by imWillX** [comment]
We have implemented the wheel animation in the private build. Feel free to take a look and suggest anything.
