### ISSUE TITLE
Dashes

### ISSUE THREAD

**Issue by ProfCube** [Hazebyte/CrateReloaded#172]
The Actual Name of the Crate
**ChrisParlYT** Found a little issue located withing the name. Lest say that on crate is named **Key-Crate** for the name of it and the other one is named **Food-Crate** well withing the load of the crate for some reason the crate will think that the __Key-Crate & Food-Crate__ are linked together, the plugin is thinking that **-Crate** is a group name and its taking anything that starts with it and will group them together. in the **IMAGES** you will see __Chriss__ image of his crate that was the problem. and at the bottom his Crates.yml is where its located to show that its with the dash that is causing it. 

| MINECRAFT VERSION | CRATERELOADED VERSION |
| ---------------------- |  :--------------------------:  |
|            v1.10.2            | Latest Version                      |

|      IMAGES     |
|----------------|
http://prntscr.com/h31786

|     CRATES.YML    |
|------------------|
https://hastebin.com/qokixofeqi.erl     (This is **ChrisPalmYT** Crates.yml)

**Comment by imWillX** [comment]
Closing this issue. 

It'd be best to use a display name for anything that has a '-'. For the crate id, try to keep it simple.
