### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by nullYoung** [Hazebyte/CrateReloaded#173]
Hi,

I'm italian and I want request you to translate CrateReloaded from english to italian. If you like this idea, you can contact me on Telegram: [@nullYoung](https://www.telegram.me/nullYoung).

Bye,
- nullYoung

**Comment by imWillX** [comment]
Wow! I love this idea. Unfortunately, I don't speak nor can I write in Italian.

If you think you can do this, please let me know!

Thanks
Will

**Comment by XXLuigiMario** [comment]
Closing this, if anyone wants a translation, they're free to open a pull request.
