### ISSUE TITLE
onetime tag variation (check receiving group instead of player opening crate)

### ISSUE THREAD

**Issue by MagmaGuy** [Hazebyte/CrateReloaded#177]
Hey I got a very strong need for a variation of the onetime tag.

On my server donators open donator crates to give donator powers to everyone. That means that often times (or in some cases every time) when they open the chests they already have the permissions themselves, but they are gifting it to the rest of the community.

Now there are quite a few of these permissions by design, which is why I really would like them to only ever drop once for as long as they are active on the lowest permission group of the server.

I am (now) aware that the onetime tag checks the permissions of the user opening the crate. This doesn't work for us as that means that donators with every permission will not be able to use the crates at all, and that the more permissions they have the less they'll be able to give.

[Conclusion/TL;DR] Would it be possible to make a variation of the onetime tag that checks the group the permission is being assigned to instead of the permissions of the player opening the crate?

(also some people seemed to have a very hard time understanding what I wanted, so in a boiled down scenario: imagine I'm an OP with all the permissions and I just want to give random temporary permissions to visitors using crates but avoiding getting duplicates of the permission nodes)

**Comment by imWillX** [comment]
A possibility would be to add a psuedo permission to a group and have the one-time tag check that permission.

Since everyone in that group has that permission, they won't receive that reward if one time tag is enabled.

Please reopen if you have any more questions.
