### ISSUE TITLE
Hide preview menu

### ISSUE THREAD

**Issue by SnowyTSW** [Hazebyte/CrateReloaded#178]
Hello 😄 Would it be possible to implement the hiding of the preview menu when left-clicking on a crate?

**Comment by LogGits** [comment]
There already is :)
Go into crate.yml and change preview.enabled to false.
https://gyazo.com/399698db91ae148fb12476c289a68f4f
If you don't see preview section simply add it in like you see in that image.

**Comment by SnowyTSW** [comment]
Thank you for your help! ^^
