### ISSUE TITLE
MasterKey, / MasterChest

### ISSUE THREAD

**Issue by Flavourized** [Hazebyte/CrateReloaded#179]
So the first part of this feature directly affects keycrates (as opposed to Mystercrate). The feature would let us make sure key which we can use on multiple crates. There would be the normal keys for each of those crates, but this key would be separate.

Next part is basically doing the opposite of above. It would allow us to use multiple keys on the same chest.

E.G

MasterKey1 opens crate1
MasterKey1 opens crate2
masterKey1 does not open crate 1

Crate1 opened by Key1
Crate1 opened by Key2
Crate1 opened by key3

**Comment by imWillX** [comment]
You can set multiple crates onto a single block.

**Comment by Flavourized** [comment]
Yeah but this idea would make a system where you can have one key open multiple crates without having to duplicate the crates in the crates.yml

**Comment by imWillX** [comment]
Are you interested in implementing this? 

We're almost there with our 2.0 update, and we'll have an API for extensions.

**Comment by Flavourized** [comment]
Yes please!
