### ISSUE TITLE
Should not error when a crate has no rewards

### ISSUE THREAD

**Issue by XXLuigiMario** [Hazebyte/CrateReloaded#182]
At the moment, if a crate has no rewards and you try to open it, you will get a NullPointerException and a message in the console saying "Message not found: crate.reward.none.".
That message should be added to the locale files, and sent to the player in case such an event were to happen. The NullPointerException should be caught and the stacktrace hidden from the console.
The message should not read like "This crate is not properly configured, contact an administrator." but instead "There are no rewards available at this time." since as I understand it, the "One Time" tag could be a cause of this situation.

**Comment by imWillX** [comment]
Should now tell the user that there are no rewards in a crate.

**Comment by XXLuigiMario** [comment]
@imWillX Will that message be added to the locale files?

**Comment by imWillX** [comment]
Yes. https://github.com/Hazebyte/CrateReloaded/blob/config/2.0.0/language/core_en.properties
