### ISSUE TITLE
Crafting Crate Keys

### ISSUE THREAD

**Issue by Lordcre** [Hazebyte/CrateReloaded#183]
Players are able to craft keys if they set the keys in slot 1 of their hotbar and then click 1 in the crafting table to place them.
 https://i.gyazo.com/30bdf7019d773fc77cf4a5a3ae347779.mp4

Server Version: PaperSpigot 1.8.8
CR Version: v1.3.97.8

**Comment by imWillX** [comment]
The hotbar should be disabled by default. Please check your config.yml to see if you enabled the hotbar.
