### ISSUE TITLE
Buycraft

### ISSUE THREAD

**Issue by Chrisgaming66** [Hazebyte/CrateReloaded#187]
When my players buy crate keys off of my store Buycraft does not fetch the command. The command is /crate giveallkey CommonKey 1. Is there something I am doing wrong?

**Comment by imWillX** [comment]
Could you check console for any errors?

**Comment by Chrisgaming66** [comment]
It just says Buycraft fetched 1 command. That command is my /alert command.

**Comment by imWillX** [comment]
I would double check your buycraft reward setup. 

If our plugin's command works normally through the console, it should work if buycraft passes it to the server. This issue would be better directed for buycraft.

http://help.buycraft.net/article/33-packages-and-commands
