### ISSUE TITLE
Virtual Keys (A new idea)

### ISSUE THREAD

**Issue by BradyMitch** [Hazebyte/CrateReloaded#19]
**Virtual Roulette Keys..**
The crate layout starts out as a screen of black glass panes, no keys. You can add a key to whichever slot you like, allowing for many key arrangements and several different amounts of keys per crate. You can also change the background item, default black stained glass pane. Each key item can be a different item, name, lore, and even have the enchanted effect.
![2016-01-31_13 13 36](https://cloud.githubusercontent.com/assets/16313579/12705054/dfed68c0-c81d-11e5-9114-74f39161cc5f.png)
![2016-01-31_13 13 40](https://cloud.githubusercontent.com/assets/16313579/12705055/e1b3c208-c81d-11e5-9470-a1ab122d2f61.png)
![2016-01-31_13 15 34](https://cloud.githubusercontent.com/assets/16313579/12705057/e510e35e-c81d-11e5-9329-a8676b5d4651.png)

**Comment by dannylif** [comment]
Yes, I want this aswell!
