### ISSUE TITLE
Minor typo; recieved -> received

### ISSUE THREAD

**Issue by mibby** [Hazebyte/CrateReloaded#191]
CrateReloaded v1.3.98.4

Noticed a typo from the console message when a scheduled command was ran to give a key to a player from console.

```
[15:45:24] [Server thread/INFO]: Crate » player has recieved MythicalCrate.
[15:45:24] [Server thread/INFO]: Crate » player has recieved MythicalCrate.
```

Upon looking to see if I can change the language file to correct the typo, I noticed you can't change the console received message.

```
# Received a crate
crate.player.recieved=%prefix%You have received a crate.
# Received a key
crate.player.keyrecieved=%prefix%You have received a key
```

Main config also has the typo here.
```
# Debugger (Developer Note: Disabled. ETA: N/A)
# Developing Use Only. Disable, if you do not want to recieve debug messages.
```

**Comment by imWillX** [comment]
Fixed in 1.3.98.5

Thanks for the report!
