### ISSUE TITLE
Potions and Player Skulls not displaying correctly.

### ISSUE THREAD

**Issue by BenBurum** [Hazebyte/CrateReloaded#196]
Hi,  I'm having a couple of issues related to the item displays.  Any kind of potion we try to put in the crate gets displayed as a generic pink potion instead of the correct color.  Here's an example line from the rewards section:
            - 'item:(373:8258 1), chance:(15), display:(373:8258 1 Potion_of_Swiftness &f%chance%)'

Is there another way to do this?  We would also like to be able to display player heads, but I'm not sure if that is possible.  Whatever we try it just shows either steve/alex or an error.

**Comment by imWillX** [comment]
Closing. Please reopen if you have any more questions.
