### ISSUE TITLE
crate wont load?

### ISSUE THREAD

**Issue by justinbea** [Hazebyte/CrateReloaded#198]
i am trying to make an csgo crate key, i have looked at crate.hazebyte.com and followed there's tutorial to make an crate, i have configurated this crate:  https://hastebin.com/wehupohefu.bash, it doenst give any error in my console, but there is no preview and cant use my key

i hope get messaged back soon

x justinbea

**Comment by imWillX** [comment]
The hastebin doesn't appear for me. Please check your link.

**Comment by justinbea** [comment]
sorry hastebin didnt work for me: https://pastebin.com/ryYc57E8

**Comment by justinbea** [comment]
sorry for dubble post but is there an answer why it isnt working?

**Comment by imWillX** [comment]
Please check your formatting of the rewards. 

* You spelled chance wrong. 
* You forget to close several of the tags.
