### ISSUE TITLE
[bug] MYSTERCRATE and redstone_ore

### ISSUE THREAD

**Issue by Flavourized** [Hazebyte/CrateReloaded#199]
**Type /ver CrateReloaded and post the output:** CrateReloaded v1.3.98.3 
**Version of bukkit/spigot/paper (type /ver):** Paper 1.11.2 b1104 
 
**Please explain your issue. How do you trigger it?**

To reproduce this issue (can reproduce with fresh files) use these steps:

1. Give yourself a MYSTERYCRATE. In default config, there is a myscrate called "FoodiePack"
2. Place a Redstone_ore block on the ground
3. Hold the "FoodiePack" mysterycrate in your hand
4. Walk on top of the redstone_ore

**Are there any errors in the console? Please use: https://pastebin.com**

There are no errors in console. 

https://i.imgur.com/V5y2nPs.gif

**Comment by imWillX** [comment]
I could've sworn that I had checks for this in 1.3.98. 

It should be fixed in 2.0.0 & verifiable by @XXLuigiMario.

**Comment by imWillX** [comment]
Closing -- Confirmed this is fixed in 2.0.

**Comment by Flavourized** [comment]
What was even the issue to cause this? This is such a random bug lol

**Comment by imWillX** [comment]
@Flavourized 

Redstone Blocks trigger the  Player Interact Event.
