### ISSUE TITLE
BUG - Sound on keycrate while not set.

### ISSUE THREAD

**Issue by kobini2** [Hazebyte/CrateReloaded#202]
Type /ver CrateReloaded and post the output: CrateReloaded v1.3.98.3
Version of bukkit/spigot/paper (type /ver): Spigot 1.12.2 (git-Spigot-4bd94dc-fb414fe) (build on 25/02/2018 00:43 GMT+1)

I haven't set any sound on my keycrate, and yet it plays a noteblock sound.

**Comment by imWillX** [comment]
Please check the effect section. If this persists, please reopen and post your the incident crate.yml.
