### ISSUE TITLE
Item exporting for display:()

### ISSUE THREAD

**Issue by Flavourized** [Hazebyte/CrateReloaded#204]
This is a QoL feature, but it would add a command which would export the item in the hand to a file in /plugins/cratereloaded/items.

The item exported would use the same format that crates.yml uses for display:(). 

This will make it easy for server owners to put items like specific potions, or items with extra long lores or tons of enchants.

**Comment by imWillX** [comment]
@XXLuigiMario I think you have an in-game editor of some sort. 
@Flavourized There will probably be a QoL open source project to make things easier.

**Comment by XXLuigiMario** [comment]
Closing this in favour of https://github.com/Hazebyte/CrateReloadedAPI/issues/25
