### ISSUE TITLE
MysteryCrate Preview system

### ISSUE THREAD

**Issue by Flavourized** [Hazebyte/CrateReloaded#205]
This suggestion will add a feature to preview the rewards of a mystery crate.

Currently, MysteryCrate will use the crate if you righ-click or left-click, and you will need to put the items which are in the crate, in the lore of the item itself. 

Maybe we can left-click to preview the items/rewards of the mysterycrate, and then right-click  to actually use it. Since the preview option already exists, if it is set to true, make it left-click to preview, right-click to use, and if preview is disabled, make both clicks use the crate. 

going from this: http://prntscr.com/imhahf
to this: http://prntscr.com/imhb69

I know that these crates are ugly af, but they get my point across

**Comment by XXLuigiMario** [comment]
```java
package me.xxluigimario.mysterycratepreviewer;

import com.hazebyte.crate.api.crate.Crate;
import com.hazebyte.crate.api.crate.CrateType;
import com.hazebyte.crate.api.event.CrateInteractEvent;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
import org.bukkit.event.Listener;
import org.bukkit.plugin.java.JavaPlugin;

public class MysteryCratePreviewer extends JavaPlugin implements Listener {

    public void onEnable() {
        getServer().getPluginManager().registerEvents(this, this);
    }

    @EventHandler(priority = EventPriority.LOWEST)
    public void onCrateInteract(CrateInteractEvent e) {
        Crate crate = e.getCrate();
        if (crate.getType() == CrateType.MYSTERY) {
            Player player = e.getPlayer();
            if (player.isSneaking()) {
                e.setCancelled(true);
                crate.preview(e.getPlayer());
            }
        }
    }
}
```

This will be easy enough to implement with the upcoming API, unfortunately, it would have to be right or left clicking while sneaking as the API for now, as it doesn't currently allow us to check which click is being used to open a mystery crate (https://github.com/Hazebyte/CrateReloadedAPI/issues/15), nor can we use PlayerInteractEvent for this instead (https://github.com/Hazebyte/CrateReloadedAPI/issues/16).
