### ISSUE TITLE
Random Number placeholder

### ISSUE THREAD

**Issue by Flavourized** [Hazebyte/CrateReloaded#206]
This suggestion is to add a randomNumber placeholder which can be used in any part of the rewards (possible even chance:()?)

Placeholder would follow this template: `%random_min_max%
Where min is the lowest amount that random number can be, and max is the highest that number could be. To keep this simple, make the returned number only be an int.

Make sure that the placeholder is the same for all copies in the rewards. Meaning, if i used %random_1_50% in the command:(), and then wanted to use %random_1_50%  onOpen:(), both of these placeholders would return the same value. 

Not sure how to handle this if a player wants 2 %random% placeholders in the same rewards line. Will leave that to you (see my pun? cus Will and Will.. sry)

Here is a couple examples:
`%random_10_255%` - Random number generated will be 10<= X <= 255
`%random_1_1000%` - Random number generated will be 1 <= X <= 1000

And some examples in the rewards:
`cmd:(/eco give %player% %random_15000_30000%), chance:(40), onOpen:(%green%&2[&aDrugRun&2]&f Prize:&a&o Ⓓ%random_15000_30000%!)`

**Comment by imWillX** [comment]
#257

**Comment by imWillX** [comment]
`alpha3`

Currently usable only in reward section.
{random:min,max}
i.e. {random:0, 5} for a number between [0,5]
