### ISSUE TITLE
Symbol Replacement

### ISSUE THREAD

**Issue by Flavourized** [Hazebyte/CrateReloaded#208]
This suggestion is to add a system where server owners can define their own placeholder to produce another character.
This is most useful for UTF-8 characters, so we don't need to go to google and find it and copy it  every time. 

```
Replacements:
  [gr]:»
  [gl]:«
  [x] = █
  [/] = ▌
  [.] = ░
  [..] = ▒
  [...] = ▓
  [p] = •
  [|] = ⎹ (thin vertical bar)
. . .
```

This is based off of holographic displays system for symbol replacements.

**Comment by imWillX** [comment]
Will be released in `2.0.35`.
