### ISSUE TITLE
Multiverse/CrateReloaded Compatibility

### ISSUE THREAD

**Issue by fred112f** [Hazebyte/CrateReloaded#209]
Every time I tp from one world to another, some crates are missing their holograms, yet still function.

**Comment by imWillX** [comment]
Notes: CrateReloaded loads before Mutliverse.

**Comment by imWillX** [comment]
Fix needs testing.

**Comment by imWillX** [comment]
Deeming Fixed. @Flavourized Test Method
```
Failed to reproduce - Steps:
- /mv unload TestWorld
- /mv reload
- /mv load Testworld

Failed to reproduce - Steps:
- /mv unload TestWorld
- /mv load Testworld

Failed to reproduce - Steps:
- /mv unload TestWorld
- Restart server (autoload: false)
- /mv load TestWorld
```

**Comment by fred112f** [comment]
When will 2.0 be released? A rough estimate, because this bug is really annoying..

**Comment by imWillX** [comment]
@Flavourized He probably has.

@fred112f We will release the update once we finish the features. Could you try to add Mutliverse to the plugin.yml dependency?

**Comment by fred112f** [comment]
Adding multiverse to the plugin.yml dependency does not change anything. This bug is halting me from releasing my server so I would appreciate a rough estimate of the fix :)
