### ISSUE TITLE
Placeholder to get # of rewards in a crate

### ISSUE THREAD

**Issue by Flavourized** [Hazebyte/CrateReloaded#213]
Suggestion is to add a placeholder which will return the number of possible rewards in the crate.

```
    rewards:
           - 'chance:(10), onOpen:(&a&lDR &8&l» &fa pile of dust..)'
           - 'chance:(50), cmd:(/ss give %player% skeleton 1), onOpen:(&a&lDR &8&l» &f1&7x &aSkeleton &7Spawner)'
```

This crate has 2 rewards, so the placeholder (maybe `%crate_rewardcount%`), will return 2. 

Intention is to use this in the lore of the key/crate. The immediate issue i see with this is that if you change the amount of rewards in the crate, any keys/crates with a different/older amount of rewards will break, but i am sure you guys could find a workaround for this. 

This is just a QoL feature.

**Comment by imWillX** [comment]
What do you mean that keys/crates with a older amount of rewards will break? 

I do know of one issue where if you change the item of the crate/key, old keys/crates will no longer register. A fix would be keeping a cache of old key attributes/etc but that may lead to unintended side effects.

**Comment by Flavourized** [comment]
@imWillX Yes that is what i mean. Older keys will not register.

**Comment by Flavourized** [comment]
I want it to be where the variable is ignored in the key, that way older keys can be used. But now that i think about it, that would require a whole other manager and that wouldnt fit within the scope of the plugin.
