### ISSUE TITLE
[Feature Request] Kick Back Custom Msg

### ISSUE THREAD

**Issue by DJ411** [Hazebyte/CrateReloaded#217]
I would like to be able to customize the kick msg for each crate i create.

As an example, if i were to have crates that only premium/ other then default ranks can get access to i want to be able to tell a user how to gain access to that crate without having to use another plugin.

Basically a multi line msg to the user if its possible.

**Comment by imWillX** [comment]
Please check the language file. These messages are sent...
```

# Unable to use the key here
crate.key.unabletouse=%prefix%You cannot use the Key here.

# You don't have the right key
crate.key.wrongkey=%prefix%You do not have a %cratename% key!
```
https://github.com/Hazebyte/CrateReloaded/blob/master/language/l_en.properties

**Comment by DJ411** [comment]
that is not what i'm asking for sadly.
