### ISSUE TITLE
[Feature Request] MonthlyCrate addon

### ISSUE THREAD

**Issue by maxlehot1234** [Hazebyte/CrateReloaded#219]
Hi I just want to know if you are able to create a monthly crates addon?

Players can claim the actual monthlycrates, but if they want more, hey can get them ine vents, rankups, top voter, top donator, baltop, etc.

It was just an idea ;)

**Comment by imWillX** [comment]
@maxlehot1234 Hey Maxle!

I'll be releasing an alpha version soon which will have a developer API. 

https://github.com/Hazebyte/CrateReloadedAPI

 I would love for this to be a feature. If you have a developer who is interested in working on this alongside the development of the project, lmk.
