### ISSUE TITLE
[2.0.0 ALPHA] Adding a toggle for Confirm Open Crate

### ISSUE THREAD

**Issue by Flavourized** [Hazebyte/CrateReloaded#222]
This will add an option per crate which will allow the server owner to select which crates he/she wants to have the Confirm option set for,

This will be useful for those who will only want the confirm option for crates like MYSTERYCRATE, or those who do not want it at all

**Comment by imWillX** [comment]
@Flavourized 

Added a toggle. Would you think that the customization of the buttons should be unique for each crate?

**Comment by Flavourized** [comment]
Yes I would suggest adding customization per crate.

I would say that a customization for the CONFIRM and CANCEL button would be enough. Although it would be easier if the placeholders could show the displayname of the crate or something that way the lore could just be "Click to confirm opening of %cratename%" .

This would make it marginally less setup time

**Comment by imWillX** [comment]
Moving custom button issue to #226
