### ISSUE TITLE
Adding a priority system inside preview system

### ISSUE THREAD

**Issue by Flavourized** [Hazebyte/CrateReloaded#223]
This will add a priority or weight system for previews. This mainly concerns multiple crates on the same block/npc, so you can sort the order of which crate you want to preview.

**Comment by imWillX** [comment]
I was thinking of adding in a weight system for the preview. 

By default, the weight will be ∞ thus anything specified with an weight will appear before the ones without a weight.

If more than one has the same conflicting weight, it'll be added in the order of the plugin. 

Config section may expand...
```
    preview:
        enabled: true
        rows: 4
```
