### ISSUE TITLE
[CrateReloaded 2.0] Missing language strings.

### ISSUE THREAD

**Issue by mibby** [Hazebyte/CrateReloaded#229]
Paper dev 1421 (Spigot 1.12.2)
CrateReloaded v2.0 - 2.0.0-alpha-05 (05/18 build)

Comparing both versions, I noticed a handful of language strings not present in CrateReloaded v2. Such as 'crate.player.nokey', 'crate.player.keyreceived', & 'crate.player.offline'. Possible a few others but haven't done a full A:B comparison. Have these messages been implemented into internal systems or been replaced outright?

CrateReloaded v1.x - CrateReloaded/lang/l_en.properties
https://paste.ubuntu.com/p/WRzgN4FQYW/

CrateReloaded v2.x - CrateReloaded/messages/core_en.properties
https://paste.ubuntu.com/p/CTckKn9gjg/

Edit: It also seems to make the attempt to save core_en.properties on every start-up.
```
[03:37:47] [Server thread/WARN]: [CrateReloaded] Could not save core_en.properties to plugins/CrateReloaded/messages/core_en.properties because core_en.properties already exists.
```

**Comment by imWillX** [comment]
Message keys are either replaced or been removed. 

Here are some examples of keys replaced ... 

| Old | Replaced |
| ------------- |:-------------:|
| crate.player.nokey | core.invalid_crate_item |
| crate.player.keyreceived | core.player_given_crate |

"crate.player.offline" is likely now an internal message. 

Will fix the error in saving properties.
