### ISSUE TITLE
[CrateReloaded 2.0] logger: true non-functional.

### ISSUE THREAD

**Issue by mibby** [Hazebyte/CrateReloaded#230]
Paper dev 1421 (Spigot 1.12.2)
CrateReloaded v2.0 - 2.0.0-alpha-05 (05/18 build)

Setting ```logger: true``` in the main config does not seem to enable any logging files. CrateReloaded 1.x generated a new file at every start-up with a timestamp.

i.e.
```
May 17, 2018 9:03:42 AM cratereloaded.bg info
```

**Comment by imWillX** [comment]
The config file is not created if there isn't nothing to report.
i.e. The config file is only created if a player opens a crate, or claims a reward.
