### ISSUE TITLE
[Feature Request] Crafting mystery crates 

### ISSUE THREAD

**Issue by Lunna123** [Hazebyte/CrateReloaded#237]
I use mystery crates extensively on my server for various purposes. One of my other plugins allows me to create custom recipes, however, since crafting crates is disabled, these custom recipes don't work.

I was wondering if it's possible to add an option to crate.yml to allow mystery crate crafting on a per-crate basis if the user has the respective permission? (e.g. cr.craft.<cratename>)

This would allow me to create custom recipes to craft these "crates". Or perhaps make it possible to do so using the new API coming?

Thanks! ^-^

**Comment by imWillX** [comment]
Hi @Lunna123 

You can enable crafting in the config.yml. Set `crate.craft` to true.

The API/impl is also available for testing.
