### ISSUE TITLE
Adventure Gamemode issue not allowing crate preview 

### ISSUE THREAD

**Issue by Flexxxxx** [Hazebyte/CrateReloaded#238]
If you're in Adventure gamemode and want to preview the contents of a crate, it does nothing at all. Opening the crate with a key works as intended, but being in adventure mode does nothing when left clicking the crate. All other game-modes work fine (excluding gamemode 3 - understandably - and the aforementioned Adventure gamemode).

**Comment by LogGits** [comment]
PlayerAnimationEvent + Getting the block the player is looking at can be used to achieve this.

**Comment by imWillX** [comment]
Notes: (Adventure Mode)
PlayerInteractEvent is triggered for right but not left click. 
PlayerAnimationEvent may be supplemental to a solution but does not differentiate between clicks. 

There's a hacky solution but i'm not going to implement it for now. Another solution would be to use /cr preview in 2.X.
