### ISSUE TITLE
Join reminder and scheduled reminders for claim

### ISSUE THREAD

**Issue by LogGits** [Hazebyte/CrateReloaded#242]
A customisable reminder that lets the user know they have claims available.

Configurable
- Boolean: Enabled?
- Boolean: Remind on join?
- Integer (in seconds(default maybe 900s aka 15m)): How long between messages to that player.
- Message that is sent

**Comment by mibby** [comment]
@imWillX Did you implement a remind-on-join message? Or is it only a remind timer?

**Comment by imWillX** [comment]
@mibby There is only a remind timer atm. 

Do you all want a join reminder as well?

**Comment by mibby** [comment]
Preferably, I would have a join reminder any time someone connects to let them know they have keys they received while offline rather than spam them with a reminder every so often. But that may just be me.
