### ISSUE TITLE
Unable to add {crate} to invalid_action message.

### ISSUE THREAD

**Issue by mibby** [Hazebyte/CrateReloaded#245]
CrateReloaded 2.0 ALPHA (published build)

With CrateReloaded 1.x, when you right clicked a crate without having a key, it outputted this message;
```
# You don't have the right key
crate.key.wrongkey=%prefix%You do not have a %cratename% &7key!
```

With CrateReloaded 2.x, it outputs;
```
core.invalid_action = {p} Error: &4You may not perform this action.
```

I'm trying to re-add this message by changing the error to;
```
core.invalid_action = {p} Error: &4You do not have a {crate} key!
```

But it does not recognize the crate clicked and only outputs ```{crate}``` in plain text.

**Comment by imWillX** [comment]
Now using: core.invalid_crate.
```
core.invalid_crate = {p} &4You do not have a {crate}.```
