### ISSUE TITLE
Option to always send keys to a player's claim box instead of to their inventory when online.

### ISSUE THREAD

**Issue by mibby** [Hazebyte/CrateReloaded#248]
CrateReloaded 2.0 ALPHA (published build)

Would it be possible to add an option to always send keys received via ```/cr give to <player> <crate> <amount>``` to a person's claim box? That way if they voted and then immediately joined an arena, they wouldn't receive the vote key while inside the arena and instead be able to claim / redeem the key while outside?

**Comment by imWillX** [comment]
#241
