### ISSUE TITLE
Unable to customize "You have already claimed that reward" message.

### ISSUE THREAD

**Issue by mibby** [Hazebyte/CrateReloaded#249]
CrateReloaded 2.0 ALPHA (published build)

When trying to claim a reward from ```/cr claim```, clicking a key to claim doesn't refresh the GUI so you can click the key again. Clicking it a second time outputs the message ```{prefix}You have already claimed that reward```.

It doesn't have a period or a space separating the prefix and the message. I _would_ add a space after the prefix in the config to ensure all messages are spaced between prefix and text (especially since v2 auto converted all legacy crate configs broadcast with {prefix}{name}), but the messages file has a space separating most prefixes already with ```{p} <message>```. So without having to remove that space from every message since that is the new default, I manually spaced apart {prefix} {name} that was converted in all crates and removed the trailing in my custom prefix. I just can't fix this message since it isn't customizable.

**Comment by imWillX** [comment]
Will be released in `ALPHA1`
