### ISSUE TITLE
Preview pagination does not work past page 1.

### ISSUE THREAD

**Issue by mibby** [Hazebyte/CrateReloaded#262]
CrateReloaded 2.0 ALPHA3

Left clicking a crate that has 2 different crates in one location, it displays both crates with an option to pick one or the other. Clicking on one fills the entire page up with items. Clicking the arrow to go to preview page 2, it is entirely empty. However it should not be empty as not everything is displayed on page 1.

**Comment by imWillX** [comment]
fixed in new build
