### ISSUE TITLE
Set HIDE_POTION_EFFECTS attribute for pagination CD item to hide lore.

### ISSUE THREAD

**Issue by mibby** [Hazebyte/CrateReloaded#263]
CrateReloaded 2.0 ALPHA 3

Setting the attribute HIDE_POTION_EFFECTS on the CD in the pagination close item would get rid of the CD's lore.

**Comment by imWillX** [comment]
If you want to add a single flag, use `flag:hide_unbreakable` in the item section.

**Comment by mibby** [comment]
Suggestion was more for the default so the CD doesn't contain the lore in all crate pagination pages. Setting flag:hide also doesn't get rid of it. You must set ```flag:HIDE_POTION_EFFECTS```.
```
    # Close Button
    # It is used to close the inventory
    close: 'GOLD_RECORD 1 name:&4Close! flag:HIDE_POTION_EFFECTS'
```

**Comment by imWillX** [comment]
I misread. I'll add that in.
