### ISSUE TITLE
Create uuid.yml file when there is a key going to that person's claim box.

### ISSUE THREAD

**Issue by mibby** [Hazebyte/CrateReloaded#264]
CrateReloaded ALPHA3

Currently whenever someone joins the server, CrateReloaded creates a new uuid.yml file in the claim folder. Instead, shouldn't it only create a uuid.yml file for a person when it needs to store a key for them? Not everyone is going to be using crates and more often than not, most people won't be utilizing the claim feature if receiving the key online.

**Comment by imWillX** [comment]
fixed in new build
