### ISSUE TITLE
end-animation: RANDOM does not function.

### ISSUE THREAD

**Issue by mibby** [Hazebyte/CrateReloaded#265]
CrateReloaded 2.0 ALPHA 3 (v2 posted late 07/19)

Setting the end animation to RANDOM for flashing reward screen in the CSGO rotation like in CrateReloaded 1.x does not function.

```
  end-animation: RANDOM
```

The end screen is static.

**Comment by imWillX** [comment]
The original key was `ending`. I'll update it to `end-animation` for consistency.

**Comment by mibby** [comment]
Just going off what it was converted to. :P

**Comment by imWillX** [comment]
Ah unintentional but another good catch.
