### ISSUE TITLE
CSGO crate rewarding does not function.

### ISSUE THREAD

**Issue by mibby** [Hazebyte/CrateReloaded#266]
CrateReloaded 2.0 ALPHA 3 (v2 posted late 07/19)

Rewarding with the new ALPHA3 build does not seem to function. When a rotation ends and it reaches a reward selection, moving into the end screen, it does not actually reward the item or command. 

Possibly broke with random variable implementation?
https://github.com/Hazebyte/CrateReloaded/issues/206.

**Comment by imWillX** [comment]
The issue was indeed #206

fixed in today's build 7/20
