### ISSUE TITLE
Option to only allow particles from one chest if multiple chests are in the same block.

### ISSUE THREAD

**Issue by mibby** [Hazebyte/CrateReloaded#267]
Would it be possible to implement an option so ```PERSISTENT``` particles don't stack on top of each other if multiple crates are in one location? Currently if you have 5 different crates all in one spot and they are each configured with a different persistent particle effect, it stacks the particles. Ideally the static effect of the first crate configured at that location would be used.

Shouldn't remove the persistent effects from the other crates since they may also be put in other places and would need an idle particle.

**Comment by mibby** [comment]
I do have a need for multiple crates being in a single location though. For example, I have a location for a boss crate but it actually has 5 different crates in the same location depending on which boss key you have for different unique boss rewards. When you right click the chest location, it opens the correct crate based on the key you are holding.

Removing the ability to set multiple crates in a location puts me in a weird position since then I would have to separate all crates that fall under the same type of category or umbrella into multiple locations - removing the convenience factor for players. :(

**Comment by imWillX** [comment]
I would need to clarify. I meant "one crate may be used in a single location at once" in that only one crate activation can happen at once. You'd still be able to set multiple crates to a single location. 

The single activation will just help with future updates that I'm planning. (aka adding holographic to key crate) #272

**Comment by mibby** [comment]
Sure, as long as it uses the open/animation/end effects of the crate that is opened in that location. :)

**Comment by imWillX** [comment]
This will be default in `alpha4`.

**Comment by mibby** [comment]
@imWillX Is it possible to define which crate takes priority when multiple are set in a block? It use to be whichever one was set first in CrateReloaded v1.x. However now, it seems to randomize each start-up which is the priority when using effects and the name reference when trying to interact without a key.

**Comment by imWillX** [comment]
Related: #223
