### ISSUE TITLE
Permission Error: CAN NOT assign cr.claim without giving them cr.base.

### ISSUE THREAD

**Issue by FrozenBeard** [Hazebyte/CrateReloaded#277]
CrateReloaded version 2.0.0-alpha5 
Paper version git-Paper-1533 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

CAN NOT assign cr.claim without giving them cr.base which then allows them to view the version and run a debug! This shouldn't be the case.
Players do not need to see or use this, they just need to "claim"

**Comment by imWillX** [comment]
This has been changed in the recent update. They should no longer need cr.base for cr.claim.

**Comment by FrozenBeard** [comment]
Its not listed on the changelog. the changelog says:


    Variables - Placeholders can now mostly be used anywhere in the crate.
    Broadcast Fix [276]
    Confirmation Menu - Add display item to the menu
