### ISSUE TITLE
No Message sent to "offline" players when they are sent a key.

### ISSUE THREAD

**Issue by FrozenBeard** [Hazebyte/CrateReloaded#278]
CrateReloaded version 2.0.0-alpha5
Paper version git-Paper-1533 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

There is no message to alert players they were sent a key when offline, so they have no feedback. They wont magically know how to "claim".

**Comment by imWillX** [comment]
`alpha7` will include a join message.
