### ISSUE TITLE
Holograms Bug

### ISSUE THREAD

**Issue by ProfCube** [Hazebyte/CrateReloaded#282]
This was when was messing around, but I noticed that when placing more than 2 crates that have holograms near each other, and you want to remove one specific crate all the other crates holograms will disappear. The only way to get beck the hologram is to do /cr reload.
[Hologram GIF](https://i.gyazo.com/3613c294445e2b5ae2355ab71876b60d.gif)

**Comment by ProfCube** [comment]
Another problem XD idk if consider this a problem but will still consider it, I noticed that when adding a lore to the crate, to put the first **lore** you need to add _{lore:0}_ instead of _{lore:1}_

**Comment by ProfCube** [comment]
This is towards the Hologram part of the crate, where it's taking interactions from the item too the actual key, I know before we use to be able to set a custom lore towards the item that the key will be. But currently while still messing around I noticed that what ever you place on:
`item: 'NETHER_STAR 1 name:&e•_&6&lDailyCrate&e_• lore:&eTo_use_this_crate_you|&ewill_need_a_&6&lDaily_Key|&6⭐&7⭐⭐⭐⭐'`
`    holographic:
        - '{crate-name}'
        - '{lore:0}'
        - '{lore:1}'
        - '{lore:2}'`
That will take affect for the Key as well, But if I were to do this:
`item: 'NETHER_STAR 1 name:&e•_&6&lDailyCrate&e_• lore:&7Click_on_a_Daily_Crate|&eTo_use_this_crate_you|&ewill_need_a_&6&lDaily_Key|&6⭐&7⭐⭐⭐⭐'`
`    holographic:
        - '{crate-name}'
        - '{lore:1}'
        - '{lore:2}'
        - '{lore:3}'`
On _{lore:0}_ it will not be displayed on the Hologram of the crate but it will be displayed on the key still completely.

If it's possible to make it so that the Hologram and the key lore would be different configuration since it's interacting with the item. I want custom lore for the item.

**Comment by imWillX** [comment]
@ProfCube The lore starts at 0 because we're programmers :).

I'll fix the holographic issue in the next update.

Also, to display code in a better format: Use three '`' i.e. ```

**Comment by imWillX** [comment]
fixed in `alpha7`
