### ISSUE TITLE
{chance} and {raw-chance} placeholders not working

### ISSUE THREAD

**Issue by klugemonkey** [Hazebyte/CrateReloaded#284]
{chance} and {raw-chance} don't seem to work in lore: option under display: for an item.
I'm noticing this on the 2.0-ALPHA6v1 release.

**Comment by ProfCube** [comment]
The {chance} one should be working, if you like pm me on discord so I can see what wrong with the {chance} on your end ok. I have tested it out for 2.0ALPHA1-6 and all work for me

**Comment by imWillX** [comment]
Fixed in `alpha7`
