### ISSUE TITLE
Sound Effect for PERSISTENT

### ISSUE THREAD

**Issue by klugemonkey** [Hazebyte/CrateReloaded#285]
for class: Sound, category: PERSISTENT, is there any way to make it so the sound is played and does not played again until play stops?   Sounds are overlapping as if the sound is just continually fired.  delay: doesn't do much as well, but should also provide a gap between end of sound and restart of sound.  IMHO, it probably should not just rapid fire sound events every tick when on PERSISTENT.  It's fine for particles, but perhaps not sound.

**Comment by imWillX** [comment]
You can add a `period` which changes the interval it fires at.
