### ISSUE TITLE
Carrot and Potato items not displaying

### ISSUE THREAD

**Issue by klugemonkey** [Hazebyte/CrateReloaded#293]
carrot and potato items are not displayed in 2.0.0-alpha8 when used in the display: section of the rewards

**Comment by klugemonkey** [comment]
Should double check all the materials that end in _ITEM.  CARROT_ITEM, POTATO_ITEM, etc.

**Comment by klugemonkey** [comment]
Does work for carrot_item and potato_item, but these are not the new 1.13 names.

**Comment by klugemonkey** [comment]
The inherent problem with converting pre-1.13 names in the configs over to 1.13 names is that pre-1.13 names for CARROT and POTATO mean different things on earlier versions than 1.13.  
If you convert earlier CARROT and POTATO to carrots and potatoes, then you have an issue when parsing the newer formatted file with CARROT and POTATO in it.
In 1.13 carrot and potato are the names assigned from CARROT_ITEM and POTATO_ITEM, but we've already converted to 1.13, so these end up being carrots and potatoes and don't show up in the display.
One way to solve is to put a version flag in the crate.yml that is checked by the item matching methods, rather than solely using the NMS version number.

**Comment by imWillX** [comment]
Will be fixed in `alpha9`.
