### ISSUE TITLE
Various potion effects not supported

### ISSUE THREAD

**Issue by klugemonkey** [Hazebyte/CrateReloaded#294]
Several 1.13 effect terminology is not working as Effect: for a potion in the display: section of a reward item in 2.0.0-alpha8.  It is still using a variant of the pre-1.13 naming for most effects.

**Comment by klugemonkey** [comment]
You probably should add the missing potions since v1_9_R2 in a new NMS class.  1.13 adds potion of the Turtle Master and Slow Falling.  
Also, you may want to change the naming for the PotionEffectTypes to the 1.13 naming depending on the NMS version and the crate.yml version.
PotionEffectType:
"speed", PotionEffectType.SPEED
"slowness", PotionEffectType.SLOW
"haste", PotionEffectType.FAST_DIGGING
"mining_fatigue", PotionEffectType.SLOW_DIGGING
"strength", PotionEffectType.INCREASE_DAMAGE
"instant_health", PotionEffectType.HEAL
"instant_damage", PotionEffectType.HARM
"jump_boost", PotionEffectType.JUMP
"nausea", PotionEffectType.CONFUSION
"regeneration", PotionEffectType.REGENERATION
"resistance", PotionEffectType.DAMAGE_RESISTANCE
"fire_resistance", PotionEffectType.FIRE_RESISTANCE
"water_breathing", PotionEffectType.WATER_BREATHING
"invisibility", PotionEffectType.INVISIBILITY
"blindness", PotionEffectType.BLINDNESS
"night_vision", PotionEffectType.NIGHT_VISION
"hunger", PotionEffectType.HUNGER
"weakness", PotionEffectType.WEAKNESS
"poison", PotionEffectType.POISON
"wither", PotionEffectType.WITHER
"health_boost", PotionEffectType.HEALTH_BOOST
"absorption", PotionEffectType.ABSORPTION
"saturation", PotionEffectType.SATURATION
"glowing", PotionEffectType.GLOWING
"levitation", PotionEffectType.LEVITATION
"luck", PotionEffectType.LUCK
"unluck", PotionEffectType.UNLUCK
"slow_falling", PotionEffectType.SLOW_FALLING
"conduit_power", PotionEffectType.CONDUIT_POWER
"dolphins_grace", PotionEffectType.DOLPHINS_GRACE

**Comment by imWillX** [comment]
Added support for these names. (`alpha9`

Just need to document them.
