### ISSUE TITLE
Update Documentation with multiple potion effect examples

### ISSUE THREAD

**Issue by klugemonkey** [Hazebyte/CrateReloaded#295]
Not able to display a potion with multiple effects in 2.0.0-alpha8.  If this is supported, please add the syntax to the wiki.
The use case is that Potion of Turtle Master requires two effects.

**Comment by klugemonkey** [comment]
Not sure the best way to do this, since you have it setup in display for effect, power and duration being unique items and you will want to have individual power and durations for each effect.

**Comment by imWillX** [comment]
@klugemonkey Here is an example: #299
