### ISSUE TITLE
effects for splash_potion and lingering_potion throws exception

### ISSUE THREAD

**Issue by klugemonkey** [Hazebyte/CrateReloaded#296]
Using splash_potion or lingering_potion as an item for the display section results in an illegal argument exception when an effect is used in 2.0.0-alpha8.

https://paste.md-5.net/gubucakigu.avrasm

The same effects with potion as the id work properly, and splash_potion or lingering_potion without effect, power, duration seem to work.

**Comment by klugemonkey** [comment]
FYI, the gamepedia wiki makes this confusing for 1.13.  There are minecraft:potion, minecraft:splash_potion and minecraft:lingering_potion items in 1.13.  But there is only a single EntityPotion that represents a projectile when a potion is thrown, so they include the Potion id into the nbt of the entity under Potion tag.

**Comment by klugemonkey** [comment]
seems like it's recognized, just doesn't work for working effects.  When using the non-working effects like instant_health, mining_fatigue and nausea, the item IS displayed as a splash potion with no effects.

**Comment by klugemonkey** [comment]
probably using .equals rather than == on an enum?

**Comment by klugemonkey** [comment]
should not use equals() to compare Material since enum implements a class and it's not guaranteed.  Best to stick with !=

**Comment by imWillX** [comment]
Should be fixed in `alpha9`
