### ISSUE TITLE
Parsing 1.13.1

### ISSUE THREAD

**Issue by Kbryst** [Hazebyte/CrateReloaded#297]
Crates reloaded: 2.0.0-alpha8
Paper 1.13.1

So I'm trying to get enchanted gear to work and I can't seem to get it to work the way the link suggests. I even just copy/pasted the example from it.

`[14:45:51 ERROR]: [CrateReloaded] An error has occurred: Parsing (0:1) [see https://hazebyte.github.io/CrateReloaded/#/config/crate?id=item-parser]
[14:45:51 ERROR]: [CrateReloaded] An error has occurred: Parsing (17:1) [see https://hazebyte.github.io/CrateReloaded/#/config/crate?id=item-parser]
[14:45:51 ERROR]: [CrateReloaded] An error has occurred: Parsing (18:1) [see https://hazebyte.github.io/CrateReloaded/#/config/crate?id=item-parser]`

            - 'unique:(), chance:(1), item:(cake 1 name:&fThe_cake_is_a_lie!)'
            - 'unique:(), chance:(1), item:(sand 1)'
            - 'unique:(), chance:(50), item:(diamond_boots 1 0:1 name:&f&nTesting_Boots lore:&bFlight_I glow:true)'
            - 'unique:(), chance:(10), display:(diamond_sword 1 17:1 18:1 unbreakable:true flag:HIDE_UNBREAKABLE)'

**Comment by imWillX** [comment]
You're right, that shouldn't work. 

The documentation is still using IDs and need to be updated for 1.13.1 #298 

Use the names like "sharpness". We'll have documentation for this shortly.

**Comment by Kbryst** [comment]
I tried using "unbreaking:1" and it did that as well

**Comment by imWillX** [comment]
@Kbryst 
Here are the spigot supported names: https://github.com/Hazebyte/CrateReloaded/issues/299
This page, https://github.com/Hazebyte/CrateReloaded/issues/299, is out of date for 1.13.

We will add a utility to include more familiar names like "unbreaking" later.
