### ISSUE TITLE
Items that are apply a effect to a player if he is holding it?

### ISSUE THREAD

**Issue by Gamecrafterhdlp** [Hazebyte/CrateReloaded#301]
Another Question :P can i create a item with a effect? 'Item:leather_boots 1..... thorns:1 effect:jump power:1 duration:2)' 

This doesnt work :/

~Max

**Comment by Gamecrafterhdlp** [comment]
Via command its possible,but i thougt it goes also that way.
Thx for the answer ;)
~Max

**Comment by Gamecrafterhdlp** [comment]
I try to create a Iron Golem Pack, which Spawns an irongolem with one click... 
But my issue is, the vanilla command /summon wont work :/
I tried also the commands /spawnmob and /spawnentity...

/spawnmob works, But if i gave this irongolem a name, it wont work anymore...

Need help! :(

~Max

**Comment by imWillX** [comment]
I'm not familiar with the spawn mob command.

Can you post what command you tried?

**Comment by Gamecrafterhdlp** [comment]
1. /spawnmob irongolem {player}
A mix between vanilla command and this Plugin, but cant add a name. 

2. only Vanille command:
/summon iron_golem ~ ~ ~ {CustomNameVisible:1b,CustomName:“{\“text\“:\“Defender\“,\“color\“,\“aqua\“,\“underlined\“:true}“}

The second point doesn‘t work...

~Max

**Comment by imWillX** [comment]
Can the normal summon iron golem include a player name?

**Comment by Gamecrafterhdlp** [comment]
I think not, but i can not try this until the command works... :/

~Max

**Comment by imWillX** [comment]
@Gamecrafterhdlp 
I was informed by a player that you can use
```/execute at {player} run summon {mob} ~ ~ ~```
