### ISSUE TITLE
CrateReloaded 1.7.X

### ISSUE THREAD

**Issue by Nykorrin** [Hazebyte/CrateReloaded#304]
I have a 1.7 spigot server but as CrateReloaded's previous versions do not work well with it, I have found one that works, but the holograms for the Crates do not show, I have installed HolographicDisplays plugin but they still do not show. Previously, it had worked when I downloaded a premade CrateReloaded plugin but only now did I find out that was LEAKED, so I uninstalled it, the free CrateReloaded plugins 1.X do not show holograms, please fix. Thank you

**Comment by WizzleBear** [comment]
No. 1.7 is EXTREMELY outdated and support for it will never be given. Please upgrade for fixes.

**Comment by imWillX** [comment]
@Nykorrin With 1.13 out, it'd be too much work to support 1.7. For a long time, I've been focusing on supporting various versions instead of creating new features. I'd like to change that focus to creating new features.

Why don't you update to 1.8?

**Comment by imWillX** [comment]
As far as I know, the free and premium version of 1.X both support holograms.

**Comment by Nykorrin** [comment]
Hm, odd, maybe it's just because 1.7 or the older versions just don't work
:/

**Comment by imWillX** [comment]
Update to 1.8 :)

**Comment by Nykorrin** [comment]
Nah, if I did, ally my other plugins may not work
