### ISSUE TITLE
Source error

### ISSUE THREAD

**Issue by imWillX** [Hazebyte/CrateReloaded#305]
Provide the file of the error

**Comment by imWillX** [comment]
`alpha9`
This will print the issue as follows
```
[04:45:04 ERROR]: [CrateReloaded] File: crate.yml, Crate: FoodChest, Section: Crate Item, Line: unkonw 1 name:[Foodie_Chest]_#124 lore:Mmmm,_something_smells_good.|Place_the_chest_down_to_obtain_a_pack_of_food! glow:true
Reason: The item material is invalid. [see https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html]
```

@klugemonkey This was your suggestion, anything else you'd like to see?

**Comment by klugemonkey** [comment]
No just as long as the user can reference the content of the line and perhaps the line number in the yml file in order to point them in the right direction and quickly resolve their configuration issues, otherwise there may be more questions directed at the forums.
