### ISSUE TITLE
Test Mode

### ISSUE THREAD

**Issue by klugemonkey** [Hazebyte/CrateReloaded#307]
Would like to see some sort of testing mode for crates.  

Could be a config setting and/or a command that toggles testing on and off.  When in testing mode, if you left-click on a crate to inspect the items in the chest, clicking on a particular item would simulate the item as a reward and run the reward line command. 

Some sort of indicator would be useful as well, perhaps in the crate's container name to show you are in testing mode as well.  

This would be a good feature to add for 2.1.0

**Comment by imWillX** [comment]
Added in 2.3.12
