### ISSUE TITLE
add command: opcommand and playercommand

### ISSUE THREAD

**Issue by svmine** [Hazebyte/CrateReloaded#312]
I want the reward to be a command that the user uses the OP in the server or the player command
For example: Opcommand
/back (not be used in console)
For example: playercommand
/menu

**Comment by imWillX** [comment]
We can add something like the player command.

For OP command, what if there isn't an OP in the server?

**Comment by svmine** [comment]
opcommand combined with type: MYSTERYCRATE will generate a plugin plugin as voucher or Coupons.
Out it found it also need if if added to execute for rights permissions only as rank DONATE
