### ISSUE TITLE
Block.yml: Not able to find world, "<world>". Queuing listener for world!

### ISSUE THREAD

**Issue by mibby** [Hazebyte/CrateReloaded#314]
CrateReloaded Pro - 2.0.0 alpha 10
Paper dev 1562 (Spigot 1.12.2)

@imWillX CrateReloaded seems to attempt to load crates before the worlds are actually fully loaded. This occurs every single time I restart / start the server. The plugin also reloads multiple times during start-up initialization.

```
	Line 98: [06:33:15] [Server thread/INFO]: [CrateReloaded] Loading CrateReloaded v2.0.0-alpha10
	Line 412: [06:33:28] [Server thread/INFO]: [CrateReloaded] Enabling CrateReloaded v2.0.0-alpha10
	Line 413: [06:33:29] [Server thread/INFO]: [CrateReloaded] Config Version: 2.X
	Line 414: [06:33:29] [Server thread/INFO]: [CrateReloaded] v1_12_R1
	Line 415: [06:33:29] [Server thread/INFO]: [CrateReloaded] Crate Configurations (11): darkzone.yml spooky.yml hat.yml suit.yml holiday.yml valentines.yml easter.yml voter.yml boss.yml mythical.yml event.yml 
	Line 416: [06:33:29] [Server thread/WARN]: [CrateReloaded] Block.yml: Not able to find world, "spawn". Queuing listener for world!
	Line 417: [06:33:29] [Server thread/WARN]: [CrateReloaded] Block.yml: Not able to find world, "darkzone". Queuing listener for world!
	Line 418: [06:33:29] [Server thread/INFO]: [CrateReloaded] [ACF] Minecraft Version: 1.12
	Line 421: [06:33:30] [Server thread/INFO]: [CrateReloaded] The plugin has been reloaded.
	Line 422: [06:33:30] [Server thread/WARN]: [CrateReloaded] Block.yml: Not able to find world, "spawn". Queuing listener for world!
	Line 423: [06:33:30] [Server thread/WARN]: [CrateReloaded] Block.yml: Not able to find world, "darkzone". Queuing listener for world!
	Line 426: [06:33:30] [Server thread/INFO]: [CrateReloaded] The plugin has been reloaded.
	Line 427: [06:33:30] [Server thread/WARN]: [CrateReloaded] Block.yml: Not able to find world, "darkzone". Queuing listener for world!
	Line 430: [06:33:31] [Server thread/INFO]: [CrateReloaded] The plugin has been reloaded.
	Line 437: [06:33:31] [Server thread/INFO]: [CrateReloaded] The plugin has been reloaded.
	Line 444: [06:33:31] [Server thread/INFO]: [CrateReloaded] The plugin has been reloaded.
```

**Comment by imWillX** [comment]
To clarify, the plugin doesn't do a full reload. It just reloads the key stash. The message will be updated for clarification accordingly.

By default, the plugin should load POST WORLD. Unfortunately, I don't have a really good solution for this startup/restart besides to delay the loading of locations. Even so, that's a terrible solution since we don't know how long a world load will take -- much less several worlds. I can improve the logic such that if multiple worlds load in succession (i.e. seconds after another), the key stash will reload only once.

**Comment by mibby** [comment]
Perhaps it is only loading post ```world``` world, i.e. the primary vanilla overworld? Is it possible to detect all worlds prior to full initialization? Or maybe have a soft dependency for all popular multi-world type plugins and load after they have?

**Comment by imWillX** [comment]
Implement two new handling in `2.0`
1. Soft-dependency: Multiverse-Core
2. Implement a 3-second delay that asynchronously waits for additional world loads, then reloads the list of set crate blocks.
