### ISSUE TITLE
Cannot Switch between "KEY" and "MYSTERY" key types. 

### ISSUE THREAD

**Issue by NolanMC** [Hazebyte/CrateReloaded#315]
Was told to report here. Going to copy paste what I originally sent: 
What happens? Cannot switch key types on crates which are already set to a block without weird issues. 

What should happen? Upon switching keytype in a config, key should be removed from locations or have a less buggy transition.

How to reproduce: 
1. Have a key configuration in crate.yml set to the key type: KEY
2. set that key to a block
3. switch the key to type: MYSTERY
4. reload the config/plugin
5. Attempt to remove that Crate from the block in game, can't due to invalid key type
6. Left or right click block that had the crate set to it previously
7. the new MYSTERY key will activate whether or not you have a key in your hand.

The hacky way to fix this is just to edit the key out with location.yml and reload the config.. but that probably shouldn't have to be done. If this goes unnoticed, a crate location could be setup to give out unlimited rewards.

GIF of this happening (items in my inventory are not the crate key that activated): https://gyazo.com/542883e4b55dc6d9da133f2c6581e17d

**Comment by imWillX** [comment]
Thanks for the report. Will be released via official `2.0` build.

We updated the location handler in various ways.

* If a crate is renamed or removed, it will be removed it from the location file.
* If a crate is not a location-based crate, it will be removed from the location.yml
