### ISSUE TITLE
Crate not working with heads

### ISSUE THREAD

**Issue by dabou0** [Hazebyte/CrateReloaded#318]
Create not working with heads, i can click to preview but if i right click with they key nothing will happen, also if i right whitout nothing in my hand, ill get the message that i dont have a key
fix asap, really good plugin, thank you

**Comment by imWillX** [comment]
Console errors, config files, anything?

**Comment by dabou0** [comment]
No console errors, the crate works normally with other blocks, I could give you configure files, but I don’t think that would help, since they work perfectly, I would say it’s just plugin side, that’s it’s not coded to support heads

**Comment by imWillX** [comment]
No, we added support for certain items a while back. 
It'd be helpful to see the crate config to know what item your key is.

**Comment by dabou0** [comment]
example of a crate: https://pastebin.com/pGPbMgsZ

Config: https://pastebin.com/jdtK0tx8

Location : https://pastebin.com/ELruaBUa

idk if is in the last version, bc i tried changing to one version before the last to see if it would work, but it didn't also
Thank you, hope you can help me solve this out

Also im not able to make speed potion show, not show, not when receiving, but for fire potion is working fine

 - 'chance:(15.0), display:(POTION 1 name:&fPotion_of_Fire_Resistance lore:&f&lchance:_15% effect:FIRE_RESISTANCE power:0 duration:180 splash:false), item:(POTION 1 effect:FIRE_RESISTANCE power:0 duration:180 splash:false)'
 - 'chance:(10.0), display:(POTION 1 name:&fPotion_of_Swiftness lore:&f&lchance:_10% effect:speed power:0 duration:90 splash:false), item:(POTION 1 effect:speed power:0 duration:90 splash:false)'

**Comment by imWillX** [comment]
set power to 1

Also, what minecraft version are you running? Do you have ViaVersion?

**Comment by dabou0** [comment]
Yes I do have via version, spigot 1.12.2

**Comment by dabou0** [comment]
also even with power set to 1 its not working

**Comment by dabou0** [comment]
Update

using last version, i joined my server, right click with a key on the crate (skull), it worked, then at the second attempt wasn't working anymore.
1.12.2 Spigot
It support 1.8 (protocol hack), but when it happened I was using 1.12
it will work all time if i'm using my hand, or holding most of  any other items (but i need to be in creative) in survival it will say i don't have a crate key
PS: it will still open the crate preview if i left click, its not reading right click

IMPORTANT: i found that the plugin its not working with some items, example when holding a random item at my hand (it wasn't a key) and clicking to open the crate it would have opened if i had a key anywhere in my inventory
but for example when trying this using a sapling it didn't worked, (creative or survival), so that's why i said some items are not working, so seeing this i tried changing my key (it was a tripwire_hook) to an armor_stand, now i am able to use heads as crates without any problems

Problem: Plugin not working with all items 
Solution: Changed my keys to an armor_stand

**Comment by imWillX** [comment]
@dabou0 Since you have fixed this, i'm closing the issue.
