### ISSUE TITLE
%displayitemname%

### ISSUE THREAD

**Issue by jordanwilliams1** [Hazebyte/CrateReloaded#319]
%displayitemname% no longer works on the latest version? It just shows up as %displayitemname% in chat? I've tried using {item} but that just shows the keys item name instead of the rewards name.

**Comment by imWillX** [comment]
Check the documentation for the latest set of variables.

It's {item}

**Comment by jordanwilliams1** [comment]
@imWillX I Don't think you read my report correctly. %displayitemname% shows the reward name in the gui. {item} shows the name of the key... 

Here's what i mean

https://www.youtube.com/watch?v=gjr7NNeHQpU&feature=youtu.be
