### ISSUE TITLE
%displayitemname% replacement 

### ISSUE THREAD

**Issue by jordanwilliams1** [Hazebyte/CrateReloaded#320]
%displayitemname% shows the reward name in the gui. {item} shows the name of the key when you open a crate.

I Want an option like in the old verison of the crate plugin where you would put %displayitemname% and it would show the rewards name. 

Here's what happens when i use {item}.

https://www.youtube.com/watch?v=gjr7NNeHQpU&feature=youtu.be

**Comment by imWillX** [comment]
Right, are you using the latest version? 

This was an issue in earlier versions of 2.0 alpha however it now prints out the display item name.

**Comment by jordanwilliams1** [comment]
@imWillX Latest version from spigot ( Sep 17, 2018 )
https://www.spigotmc.org/resources/pro-crate-reloaded-mystery-crate-1-8-1-13-1.3663/updates

**Comment by imWillX** [comment]
Let's see your crate.yml.

**Comment by jordanwilliams1** [comment]
@imWillX Sorry was really busy the past week. Here's my crate.yml: https://pastebin.com/FKkQAbGg

**Comment by Disorbs** [comment]
Already reported this few months back when it was upgrade to 2.0 and said it was going to fixed but still waiting and i recently brought it up to them in discord so they know about it and said it should be fixed on the next update lets cross our fingers :)

**Comment by imWillX** [comment]
Fix will be released in `2.0.1`
