### ISSUE TITLE
Backpack / Gui Incompatibility

### ISSUE THREAD

**Issue by harry0198** [Hazebyte/CrateReloaded#321]
So, using a plugin called MinePacks you can put your crate keys in your backpack for storage. However, once you try to take them out they shoot back into your back pack and you can't use them. I'm assuming this is with all general gui plugins and hopefully you can make the crates compatible with the plugins. Thanks a lot!

**Comment by imWillX** [comment]
What do you mean by shoot back into your backpack? 

Our plugin doesn't touch GUIs outside of our plugin or shulkers specifically for crate interactions. How other plugin handles the crate item is on that plugin.

**Comment by imWillX** [comment]
Closing, no response.
