### ISSUE TITLE
Right-click with a key 

### ISSUE THREAD

**Issue by WizzleBear** [Hazebyte/CrateReloaded#325]
When pointing at nothing, right-clicking the key will spam the "Can't use that here" message. Anyway to prevent that?

**Comment by Disorbs** [comment]
mine was working fine and it also started to do this using NPC Crate not sure about regular block crates.

and no errors

**Comment by imWillX** [comment]
@Disorbs Is this specific to having NPC crates installed?

**Comment by Disorbs** [comment]
> 
> 
> @Disorbs Is this specific to having NPC crates installed?

hmm it could be it seems to do it on my npc but on a normal chest crate it works fine? 
[https://i.gyazo.com/3430d2605868b43a1b70c12eee2a7db6.gif](url)
