### ISSUE TITLE
Small Errors

### ISSUE THREAD

**Issue by ProfCube** [Hazebyte/CrateReloaded#329]
**Error on right click:**
When clicking an NPC when i don't have a Key it shows me 
`[Crate] Error: You may not perform this action`
People have been getting a little worried about this an want to make sure its not a bug or a small error. While at the same time when you use a key on the NPC it will display in chat 
`
[Crates] You may not use FoodKeyT3(Crate i was using) here. 
`
This may also happen with just regular crates at the same time, but so far nothing else has been happening with it so far.
**GIF Example on NPC:**
[https://i.gyazo.com/0d6d3634f79382e10eecb55cb6b23a8a.gif](https://i.gyazo.com/0d6d3634f79382e10eecb55cb6b23a8a.gif)

**Comment by Disorbs** [comment]
**Crate:** 2.0.0
**CrateNPC:** 1.0.1
**Citizens2:** Dev Builds

**Right-Click npc with no key**
[Crate] Error: You may not perform this action

**Example:**
[https://i.gyazo.com/1d7b2ef62afcd7b7e50e726d2d273da7.gif](url)

Messages.yml:
[https://hastebin.com/tuhabewela.coffeescript](url)

**Comment by imWillX** [comment]
NPC issues are here: https://github.com/Hazebyte/CrateReloadedNPC

This is also already reported but i'll keep note. https://github.com/Hazebyte/CrateReloadedNPC/issues/2
