### ISSUE TITLE
Logger

### ISSUE THREAD

**Issue by klugemonkey** [Hazebyte/CrateReloaded#331]
Looks like you are using Bukkit logger instead of plugin logger.  Please fix because the message it's putting in the log is "Plugin is out of date. Running 2.0.0, Latest 2.0.1." and has no plugin prefix. It's preferred to use this.getLogger() in your onEnable() instead Bukkit.getLogger() as it will automatically prefix with your plugin name.

**Comment by imWillX** [comment]
Fixed in `2.0.3`
