### ISSUE TITLE
Chance Variable No Longer Working

### ISSUE THREAD

**Issue by NolanMC** [Hazebyte/CrateReloaded#332]
Crate Reloaded Version: 2.0.1 Pro
Server Version: Paper 355 (1.13.1)
Crate: https://paste.md-5.net/kikomelowu.sm
Image showing the issue: https://i.imgur.com/71cxGTx.png

The chance placeholder is no longer parsing chance on crate preview and on actual use of a key.

**Comment by Momshroom** [comment]
This is also an issue in the free version.

**Comment by imWillX** [comment]
Fix is released in `2.0.2` on spigot
