### ISSUE TITLE
Async Hologram Creation Error on Startup

### ISSUE THREAD

**Issue by NolanMC** [Hazebyte/CrateReloaded#333]
Crate Reloaded Version: 2.0.1 Pro
Holographic Displays Version: 2.3.1-SNAPSHOT
Server Version: Paper 355 (1.13.1)
Error: https://paste.md-5.net/netemaveco.avrasm

Not sure if this would be solved by updating my Holographic Displays version, but this error appears on startup, even though I don't make use of Holograms for any of my crates.

**Comment by NolanMC** [comment]
Issue persists with latest version of Holographic Displays and version 2.0.2 of Crate Reloaded.

**Comment by imWillX** [comment]
Fixed in `2.0.3`
