### ISSUE TITLE
Crate claim notify bug

### ISSUE THREAD

**Issue by Disorbs** [Hazebyte/CrateReloaded#338]
So for some reason if you use the offline flag while giving a crate key and the player is online
he wont receive the messages about claiming it with /Cr Claim only if the actual player was offline.

1. Use **/cr give to <player> <key> 1 offline** while he is online
2. he wont receive the crate claim notification even after re-logging

To get it to work you muse do it while they're offline and it will work

**Comment by imWillX** [comment]
Will be fixed in `2.0.3`
