### ISSUE TITLE
Mystery crates items are given even when there is not enough space

### ISSUE THREAD

**Issue by danjono** [Hazebyte/CrateReloaded#345]
Minecraft version: git-Spigot-2474d93-e693496 (MC: 1.13.2) (Latest at time of writing)
Plugin version: 2.0.3

If a player attempts to open a mystery crate when their inventory is full it will correctly tell them their inventory does not have enough space and blocks opening it.

If however say the player has 1slot available in their inventory and the crate they open was to reward them 5 items from it the player would only get 1 item and the rest are lost.

Edit: Also noted that if a crate is opened in the air it will allow it even without enough space and the items and crate are lost. If it is placed on the ground the error message that there is not enough space shows.

**Comment by danjono** [comment]
Any further updates on this? Still finding that items can be lost when opening on a full inventory.

Also to add to the above while it will always do this when opening while clicking air, if you attempt to place the crate to open it it will tell you then you don't have enough space if you have zero space. If you have one inventory slot free it will open it and only give you one item and the rest will be lost.

**Comment by imWillX** [comment]
Fixed open on air block `2.0.8`

**Comment by imWillX** [comment]
Rewards regardless of cmd or item are sent to claim if there are no space in inventory.
