### ISSUE TITLE
Giving online players 'offline' crates does not alert them in game

### ISSUE THREAD

**Issue by danjono** [Hazebyte/CrateReloaded#346]
Minecraft version: git-Spigot-2474d93-e693496 (MC: 1.13.2) (Latest at time of writing)
Plugin version: 2.0.3

If you were to give a player a crate as if they were offline, they will not receive an instant notification in-game and will only receive it if they re-log.

For example: /cr give to <PLAYERNAME> <CRATENAME> 1 offline

It will also incorrectly tell the sender of the command the player is not online.

**Comment by imWillX** [comment]
The user will now receive an instant notification `2.0.4`
