### ISSUE TITLE
[Feature Request] Give players a crate to claim when their inventory is full

### ISSUE THREAD

**Issue by danjono** [Hazebyte/CrateReloaded#347]
Currently, the plugin will drop the crate on the floor for the player if their inventory is full. I personally don't think this is a great solution if the player is not paying attention to chat for the notification or is moving at the time and misses the message.

I would suggest a better solution would be to have an option to give the player a crate to claim instead if their inventory is full so they do not potentially miss out.

**Comment by LogGits** [comment]
:o I thought it already did this. This is a needed feature as it prevents key loss.
