### ISSUE TITLE
Problem with the PlayerInteractEvent in 1.8.8

### ISSUE THREAD

**Issue by HiKingsFR** [Hazebyte/CrateReloaded#348]
**#Update:** Read my message below.
(https://github.com/Hazebyte/CrateReloaded/issues/348#issuecomment-437591792)

**Comment by imWillX** [comment]
What ender pearl plugin are you using?

Please provide the direct link.

**Comment by imWillX** [comment]
Are you still able to throw the enderpearl?

**Comment by HiKingsFR** [comment]
Yes i'm still able to throw them but i want to cancel them.

**Comment by HiKingsFR** [comment]
I will re-explain the problem quickly.

For example, in my case I want to block the interaction with an enderpearl.
It's very easy to do. I have to check the item and cancel the event.

> Screenshot in game: http://prntscr.com/lgoi0k
> Screenshot of the code: https://prnt.sc/lgoiye

**Comment by HiKingsFR** [comment]
**Summary of the problem.**

For example, in my case I want to block the interaction with an enderpearl.
It's very easy to do. I have to check the item and cancel the event.
This solution works perfectly!

But the problem is that it does not work anymore since I installed CrateReloaded.
I tested several versions. The bug appears after version 2.0 of the plugin.

The problem is that the event is not cancelled. Event with priority = EventPriority.HIGHEST. I have this same problem with all the plugins that cancel the PlayerInteractEvent.


On these screenshots you can see the problem. I want to cancel the event but it does not work and the enderpearls are launched.

> Screenshot in game: http://prntscr.com/lgoi0k
> Screenshot of the code: https://prnt.sc/lgoiye

More information:
_- Version: Spigot 1.8.8
- Plugins: Vault, LuckyPerm, Essentials-2.x-SNAPSHOT.
- Tested Server 1: I7-4790K 4Go RAM in localhost.
- Tested Server 2: Amd ryzen medium cpu 1Go RAM 50ms._

**Comment by imWillX** [comment]
@HiKingsFR I ran a similar setup.

Version: https://i.imgur.com/62ZkD4C.png
Attempt to throw ender: https://i.imgur.com/QuSOYHj.png
It is canceled for me.

The code is exactly the same as yours. I ran with both NORMAL and HIGHEST priority.

**Comment by imWillX** [comment]
Fixed. Made changes to code handling skull interactions. 

This may have broke #88 (?).
