### ISSUE TITLE
Parsing issue with the Lore tag in display commands

### ISSUE THREAD

**Issue by DXUltimate** [Hazebyte/CrateReloaded#349]
Hi, I am on v2.0.3

I wanted to report this as I was unsure why it was doing this. This only happens when I try to add a preset Lore to an item in the cmd:() . For whatever reason, the GUI display keeps trying to pull from the display tag in the cmd:() instead of the display:() . Allow me to elaborate;

Command used: give {player} minecraft:diamond_sword{repairCost:"75000",Enchantments:[{id:"minecraft:fire_aspect",lvl:3},{id:"minecraft:unbreaking",lvl:1}],display:{Name:"{\"text\":\"§4§lFiery Gaze\"}",Lore:["A true one-of-a-kind weapon."]}} 1

Line in config:             - 'unique:(),     chance:(2),          cmd:(give {player} minecraft:diamond_sword{repairCost:"75000",Enchantments:[{id:"minecraft:fire_aspect",lvl:3},{id:"minecraft:unbreaking",lvl:1}],display:{Name:"{\"text\":\"§4§lFiery Gaze\"}",Lore:["A true one-of-a-kind weapon."]}} 1) display:(diamond_sword 1 name:&4Fire_sword! lore:A_true_one_of_a_kind_weapon! glow:true)'

Result: https://puu.sh/BZLG2/0ceebb8092.png

Removing the preset lore fixes it, but I would love to add preset lore to my items when players win them. IT would give them unique and interesting items. =3

Thanks again!

**Comment by imWillX** [comment]
You're missing a comma after the command tag.
