### ISSUE TITLE
Mislabeled Material Names (1.8-1.13)

### ISSUE THREAD

**Issue by imWillX** [Hazebyte/CrateReloaded#355]
Please provide the following information...

**Server Version:**
**Expected Material:**
**Current Material:**
**Input Value:**

i.e. 

**Server Version:** 1.13
**Expected Material:** purple_shulker_box
**Current Material:** light_purple_shulker_box
**Input Material:** purple_shulker_box

**Comment by ecoterrorist** [comment]
Server Version: 1.13
Expected Material: lime_shulker_box
Current Material: Error, plugin disables
Input Material: lime_shulker_box

Server Version: 1.13
Expected Material: green_shulker_box
Current Material: Error, plugin disables
Input Material: green_shulker_box

**Comment by imWillX** [comment]
Server Version: 1.8
Expected Material: CAULDRON
Current Material: AIR
Input Material: CAULDRON

**Comment by imWillX** [comment]
Fixed shulker boxes, cauldron.

@Germanode I was able to reproduce the issue for llamas however I can't find the issue. Does this occur for any other spawn eggs?

**Comment by Germanode** [comment]
> Fixed shulker boxes, cauldron.
> 
> @Germanode I was able to reproduce the issue for llamas in 1.12 however I can't find the issue. Does this occur for any other spawn eggs?

Yes. It happens to Polar Bear eggs as well. (383:102). 
It works normally for Rabbits (383:101) and Horses (383:100) tho.
