### ISSUE TITLE
/cr give to {player} "cratename" breaks the reward screen

### ISSUE THREAD

**Issue by ARchonSpigot** [Hazebyte/CrateReloaded#361]
if you use /cr give to {player} "cratename" the reward screen breaks and you are stuck in it untill you are kicked, and can not open any more crates until the server is restarted.

Useful for giving a rare chance at some special crates

**Comment by imWillX** [comment]
Which crate animation?
Error Log? 
Please provide a crate.yml

**Comment by imWillX** [comment]
Closing. Unable to reproduce the issue.
