### ISSUE TITLE
Moving items into a Shulker box with Numbers [1][2][ect]

### ISSUE THREAD

**Issue by Disorbs** [Hazebyte/CrateReloaded#371]
So when you place down a normal shulker box and try to transfer items using your number keys
when you hover over an empty slot inside the shulker box and use the keys you get a 

"Crates: error: you many not perform this action with shulker boxes"

same thing with keys when you're creative and double tap the [x] to dispose everything in your inventory you get a 

"Crates: error: you many not peform this action with shulker boxes"

Latest version

**Comment by imWillX** [comment]
Intentional behavior. I'll hvae a toggle in `2.0.8`

Don't know if there is still duplication issues with shulker boxes but I added a toggle.

In config, chance "crate.shulker-hotbar" to false.
