### ISSUE TITLE
Incorrect Item Displayed 1.13.2

### ISSUE THREAD

**Issue by WeatherSquad** [Hazebyte/CrateReloaded#372]
I have this line of code in the crates.yml file but it displays as turtle shell in the gui

`- 'unique:(),     chance:(25),         item:(stone 64), display:(stone 64 name:&2Stone_x64 lore:_|&eChance_25%)'`

#
![screenshot 2019-02-11 at 13 39 50](https://user-images.githubusercontent.com/25124064/52566817-a2f09980-2e02-11e9-9073-ee3315d36ee8.png)

**Comment by imWillX** [comment]
#355

**Comment by imWillX** [comment]
Fix will be released in `2.0.9`
