### ISSUE TITLE
Cannot move crate keys in survival

### ISSUE THREAD

**Issue by marvic2409** [Hazebyte/CrateReloaded#380]
When creative control is disabled (Or enabled), players in survival cannot use their hotbar to move their crate keys. They are able to move the crate keys with mouse. They are also able to move the keys into an empty spot using their hotkey. But when they try to move the keys into a item, it gives the error message "Error: &4You may not perform this action." Here is a video: https://streamable.com/j3x9r

**Comment by imWillX** [comment]
Enable these two keys in config
```
crate:

  shulker-hotbar: true
  hotbar: true
```
