### ISSUE TITLE
Being able to skip an animation

### ISSUE THREAD

**Issue by tomkeuper** [Hazebyte/CrateReloaded#381]
I want to have a couple CSGO crates that players can open when they buy keys or get them from voting. But when someone buys 64 keys he will need to wait for evert animation to finish. So my suggestion is; being able to skip an animation by pressing the 'esc' key. 

Thanks,

Mr Ceasar
Mr. Ceasar#9372

**Comment by imWillX** [comment]
Hi,

This is already possible. Check the config key: crate.peri-exit and turn that to true.
