### ISSUE TITLE
{item} variable does not work correctly with MYSTERY Crate

### ISSUE THREAD

**Issue by jonsjonsjons** [Hazebyte/CrateReloaded#382]
Hello,

Normally the {item} variable returns the item that the player has won. But with Mystery crates, it instead returns the Crate name itself. 

So let's say you won item:DIAMOND from crate:KEYCRATE , the {item} variable would return whatever the DIAMOND is named and {name} would return whatever the KEYCRATE is named.

But with MYSTERY crates, the {item} and {name} variables return the same thing: the name of the KEYCRATE. {item} does NOT return the name of the reward like it should.

I'm assuming it's because the plugin returns the name of whatever is held by the time the variable is called, but Mystery crates simply put the reward NEXT to the held item slot. I know this is for the purpose of opening multiple Mystery crates, but please try and fix this bug! Thanks

**Comment by imWillX** [comment]
@jonsjonsjons The item variable seems to work fine for me.

Could you provide a version number and crate config?

/about cratereloaded

**Comment by jonsjonsjons** [comment]
Hi Will, the version number is 2.0.7, the latest free version of CrateReloaded.
Here's the config: https://pastebin.com/wdzT8QE4

**Comment by imWillX** [comment]
@jonsjonsjons It uses the name of the item. You don't have a display variable with a name on any of rewards.

It won't be able to figure out the name.

**Comment by jonsjonsjons** [comment]
My mistake Will. Thanks for helping me out
