### ISSUE TITLE
(more) API suggestions.

### ISSUE THREAD

**Issue by luwie556** [Hazebyte/CrateReloaded#388]
PreviewCloseEvent - Something small but a good thing for devs. Calls when player closes a preview inventory.

CrateOpenEvent - Called when player opens a crate.

CrateEndEvent - Called when player is done opening a crate. (When end animation is done)

**Comment by imWillX** [comment]
We're rebuilding our inventory system using [Base](https://github.com/Hazebyte/base/). 

We will be implementing these calls once we're done.

**Comment by imWillX** [comment]
`2.0.17` https://github.com/Hazebyte/CrateReloadedAPI/issues/34
