### ISSUE TITLE
Item Recognition 

### ISSUE THREAD

**Issue by TheGlitchedMob** [Hazebyte/CrateReloaded#392]
CratesReloaded 1.13X

Hello!

When creating a new consumable crate in the crates.yml file, I tried to use records as the item and the plugin wouldn't recognize the item listed. I have tried to use all of the records (record_mall, record_cat, record_chirp, etc.) and none of them seem to work. When switching the item to any other item ID, the plugin recognized it immediately once I reloaded the plugin on my server. I didn't know if this was a know issue or not, but i wanted to let the developers of the plugin to know and hopefully resolve the issue!

Regards,
    The_Glitched_Mob

**Comment by imWillX** [comment]
Hi,

Please look at:

https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

They are no longer called records -- they are called discs.
