### ISSUE TITLE
[Recommendation] Admin Retrieval

### ISSUE THREAD

**Issue by ethan-w-foshee** [Hazebyte/CrateReloaded#394]
I wasn't entirely sure how to word this, but this was the best way I thought:

Could we get an addition where you can (as OP) run a command that lets you retrieve items directly from a chest. So that way, if you need to get a specific item out of a chest, you can just run this command? Or open an Admin Menu? I can try to elaborate more if needed.

**Comment by imWillX** [comment]
Something like a preview menu but you can take items out of it?

**Comment by StarZlinger** [comment]
Yes. Exactly like that. As long as you have a permission for it.
