### ISSUE TITLE
Crate reward item moves over a slot

### ISSUE THREAD

**Issue by 0xC1A551C** [Hazebyte/CrateReloaded#399]
It would be nice if you could fix this or change this.

When using mystery crate items are moved to a different slot rather than taking up the slot the mystery crate was in. In the images below the diamond pickaxe is a crate that gives a diamond pickaxe. The first image is the crate and when you right-click to open it you a given a diamond pickaxe which is moved to the second slot rather than filling the first slot.

![Screenshot from 2019-06-01 19-37-12](https://user-images.githubusercontent.com/36227001/58756040-f87dae80-84a4-11e9-9cce-4dc1556388e4.png)

![Screenshot from 2019-06-01 19-37-23](https://user-images.githubusercontent.com/36227001/58756041-fa477200-84a4-11e9-8bf6-b77f93983d16.png)

**Comment by imWillX** [comment]
Will be fixed in `2.0.15`
