### ISSUE TITLE
Virtual Keys

### ISSUE THREAD

**Issue by Elumis** [Hazebyte/CrateReloaded#4]
Have an option for having keys stored in virtual GUI instead of as items in game. When they open the chest in game it'll check if they have the proper keys in there profile.

Example of a GUI:
![](https://i.gyazo.com/71adcdc3495381bf93dcc4f492d89ef1.gif)

People have been requesting virtual chests as well but for my needs I'd prefer to keep the option for a physical chest to be used with virtual key. 

I have my worlds inventories separated and my idea is that I could have a player given 5 Keys and they can use them in "world A" on a crate chest and then the rest in "world B" on a different crate chest. Making the player choose were they want to spend the rewards.

**Comment by vampirictorch** [comment]
Great idea! I would love it built in too however until it becomes a feature you could use this plugin as a temp alturnative? ^^ until Dino decides to make it a possibility. https://www.spigotmc.org/resources/chestmaster.3157/
