### ISSUE TITLE
Holograms bug

### ISSUE THREAD

**Issue by slvlr** [Hazebyte/CrateReloaded#400]
Hey, is this an issue with crates or holograms? https://pastebin.com/VsmTkbr6   - other Holograms plugin doesn't work either

**Comment by imWillX** [comment]
I don’t believe this is a cratereloaded issue. Try upgrading  holographics.

**Comment by slvlr** [comment]
This was using their latest dev build

**Comment by imWillX** [comment]
We’re just making calls to hd. I’d report this issue to hd.
