### ISSUE TITLE
add event CrateOpenEvent

### ISSUE THREAD

**Issue by XxWill33xX** [Hazebyte/CrateReloaded#401]
Hello,

After many tests, I found that the ClaimEvent vent does not detect the opening of a safe and that the event CrateInteractEvent is not suitable for what I'm looking for. I would need to vent "CrateOpenEvent" which is call when a player successfully opens a safe. My usefulness will be to display an opening message to the players having activated a preference to display the messages of openings of the coffers.

Thank you ;)

---

Bonjour,

Après de nombreux test, j'ai constaté que l’évent ClaimEvent ne permettez pas de détecter l'ouverture d'un coffre et que l'événement CrateInteractEvent n'est pas adapté à ce que je recherche. Il me faudrait en évent "CrateOpenEvent" qui est appeler lorsqu'un joueur ouvre avec succès un coffre. Mon utilité serai d'afficher un message d'ouverture aux joueurs ayant activé une préférence d'affichage des messages d'ouvertures des coffres.

Merci ;)

**Comment by XxWill33xX** [comment]
up

**Comment by imWillX** [comment]
Duplicate issue

Will track issue here:
https://github.com/Hazebyte/CrateReloadedAPI/issues/34
