### ISSUE TITLE
Messages Issues

### ISSUE THREAD

**Issue by pvpstryker** [Hazebyte/CrateReloaded#407]
Not being able to modify text in the plugin.
Examples are, the confirmation GUI: https://gyazo.com/36b7da525e6c32df22317ead8fa7aaa7
Other example is giving a key to someone that isn't online: https://gyazo.com/bf4627626ef033789ab82ea973cef322
Another example is the claim GUI, everything below the item name and lore: https://gyazo.com/d60ea3eb020d3367d1f9b2bff816229a
Other example would be in the core_en {crate} should refer to the display name and not the actual config name of the crate: https://gyazo.com/0edd9798bd04a78fef51d8a22d967e46
https://gyazo.com/608707370a77545a329a55ac01b8b671

**Comment by ProfCube** [comment]
Has been listed here before 
[https://github.com/Hazebyte/CrateReloaded/issues/406](Issue #406 Confirmation GUI)

**Comment by pvpstryker** [comment]
#406 has been closed. Check the new one.



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by imWillX** [comment]
Confirmation menu: Check the config `crate.confirmation-menu`
Claim items: Will add support for this
{crate} refers to identifer while {crate-name} refers to the display name.
