### ISSUE TITLE
Add the ability to not give players items shown in preview crate

### ISSUE THREAD

**Issue by Bowbuck2** [Hazebyte/CrateReloaded#408]
Hello,

I was hoping for a feature implementation where you can add a tag to the item like give:(true/false) similar to the glow tag. I would like this feature since all of my rewards in my crate are given to the player via command, and I only have items set up so players can see possible rewards from that crate.

I could setup a system where players could right click the items given to them from the crate system but this would open up new issues such as players sharing rewards with other players, I feel with a system that could stop giving items to the player when they are just command rewards would be a great addition to this plugin

Thanks for reading!

**Comment by imWillX** [comment]
use the display tag.
