### ISSUE TITLE
particle desync? for cratereloaded

### ISSUE THREAD

**Issue by runescapejon** [Hazebyte/CrateReloaded#415]
Hello for cratereloaded i get this randomly https://gyazo.com/6d7c879ad41ed217bd79a108b32c9620
it seem that the particle are not in sync with the chest. This happen randomly and the best way i know how to fix it is to restart the server any idea how to fix.

Config: https://pastebin.com/raw/VAFADpDd
CrateReloaded version: 2.0.15
Paperspigot: 176

**Comment by imWillX** [comment]
Attempt Fix: Testing

**Comment by imWillX** [comment]
Assuming this is fixed.
