### ISSUE TITLE
Server crash by Crates?

### ISSUE THREAD

**Issue by Disorbs** [Hazebyte/CrateReloaded#416]
I think my server crashed from CR trying to give out a book from another plugin not sure why it always lags when it try to do it via Crates, TE dev said looks like crate is lagging during  the process of json reading.

Crash log: https://paste.md-5.net/hicamopiju.md

version: 2.0.14 (unless the new version deals with this doubt it matters im one version behind)

**Comment by imWillX** [comment]
@Disorbs Does this only happen when you give out something from TE?

**Comment by Disorbs** [comment]
yeah only when giving out with TE - Crate https://paste.md-5.net/ludejateci.rb

**Comment by imWillX** [comment]
Closing, please reopen if the issue persists. 

I'm not too sure what the dev from TE meant when they mentioned json reading. We just execute the command and pass it to the console.
