### ISSUE TITLE
No Reward Error With Crate Reloaded Double Crates/Possibly Single?

### ISSUE THREAD

**Issue by Frostified** [Hazebyte/CrateReloaded#421]
Currently only  affects double crates(voting crates combined placing next to eachother), havent tested single.

Upon placing 2 voting chest next to each other on my server to make a double chest, sometimes players get nothing. Its set at 1 to 3 items(for reward chances) and if you place them to make a double chest and dont open it till its a double chest, sometimes the chest is blank/empty with nothing in it, no rewards, nada...

Crates work:
[0;30;1m[[0;36;1mCrates[0;30;1m][0;33;1m You have given a VoteCrate to Sleepyflea. [0;35;22mSTATUS: [0;32;1mSUCCESS.[m[m

No error line was outputted in my logs when the blank chest happens. I can show someone if they can hop on my server.

My crate.yml:
https://pastebin.com/csRtgJdV

**Comment by imWillX** [comment]
This might be because you have commands. We aren’t able to display commands so there just given to the player.

**Comment by imWillX** [comment]
User confirmed above solution fixed it.
