### ISSUE TITLE
MysteryCrate Problems

### ISSUE THREAD

**Issue by BigCDG** [Hazebyte/CrateReloaded#422]
Hello, I have 2 bugs to report regarding the MysteryCrate setting.

At the beginning of the video attached I show that right-clicking and left-clicking do different things if your inventory is full. That is bug #1. The second one I'm confident is a bug, but I might be configuring this wrong. Left-clicking with a full inventory sends the rewards to /cr claim. When I go to /cr claim, it only has 1-3/4 items. Here is my config, when using the crate without full inventory it gives all of the items all the time. 
https://pastebin.com/C46xtr0N - crate.yml
https://pastebin.com/eu91zSjh config.yml

Video of bugs: 1st and 2nd bug > https://youtu.be/3XFEOfEeMC4

Another bug is that when you set 
 handle-full-inventory: true
To false, the items just disappear.

Video: https://youtu.be/G1ambIqB2AQ

Thanks for reading through all of this <3

If you need anymore info, just reply!

**Comment by imWillX** [comment]
Hi @BigCDG 

Thanks for reporting this issue. What do you mean by 1-3/4 of the items? Is this 1 of three rewards?
