### ISSUE TITLE
Suggestion: Cycle through all available rewards instead of showing rewards based on how common they are (mysterycrate)

### ISSUE THREAD

**Issue by FixTheAdmin** [Hazebyte/CrateReloaded#424]
Love the plugin, just have a small suggestion. Right now mystery crate only cycles through rewards based on rarity. Very rare rewards are therefore not shown very often. It would be nice if all available rewards would be shown.

**Comment by imWillX** [comment]
We implemented this because someone mentioned that rare items were shown too much. Will not be reverting this change.
