### ISSUE TITLE
Shulker Boxes and CrateReloaded 2.0.17

### ISSUE THREAD

**Issue by AmazedMender16** [Hazebyte/CrateReloaded#427]
you cannot move items out/in a shulker when hovering over and pressing a number from 1-9 ( for example stone blocks )

**Steps to reproduce:**
Open a sulker and hover over and item, then press 1 for example.
You will get the message that you cannot store your crate keys in there while they are just stone blocks.

**Plugin/Server Info:**
CrateReloaded 2.0.17 ( paid one )
Server version: 1.14.4

**Comment by imWillX** [comment]
Fixed in `2.0.22`
