### ISSUE TITLE
adding support of 1.14.4 customModelData

### ISSUE THREAD

**Issue by dryter97** [Hazebyte/CrateReloaded#429]
Custom Model Data is a nbt allowing to change a picture or model display for specific item without binding has the old way with damage. Obiviously damage is doing it great but i think for the new 1.14.4 ressource pack support it could be nice. i dont think it will be easy but i mean if you are able to look at nbt of specific item and allowing people to add value on display could be nice.

what im suggestion its adding the display feature to use custommodeldata on a ressource pack and crate reloaded.

the purpose is to be able to use plugins like magic or itemsadder or newitems(this one is based on damage but you know what i mean) to diplay most like what the player should get obiviously.

it could allow me to show a realm minecraft broom instead of a stick (obiviously its the nearest i could get so :x )

there is the website referencing custom model data: 
[https://www.planetminecraft.com/forums/communities/texturing/new-1-14-custom-item-models-tuto-578834/](https://www.planetminecraft.com/forums/communities/texturing/new-1-14-custom-item-models-tuto-578834/)

and there is a demo of a  ressource pack using custom model data:  
[https://uc1b976b89f71bbea074d3073235.dl.dropboxusercontent.com/cd/0/get/AqtKELN6MHOm-BurW9mQw8LH-rAmSu4SRaGgohWlxRMn3wxWnR9dtj26V-w-Rz-L8GVpMPwpJr7UD5y3staaYHnd3_Y2tDg_dGVyqc8OhGyiUg/file?dl=1#](url)

Simply a carrot you ill see.

you canprety much give it to you with a vanilla command getting the custom model data value on the command.

Good Luck!

**Comment by imWillX** [comment]
This should be added in `2.0.21`. Please reopen if there are any issues.

**Comment by blek-id** [comment]
Doesn't work on latest pro version

**Comment by dryter97** [comment]
Still this feature is not existing be sure ill close the post when it will work. Btw its an nbt tag. Should be easier than you expect.
