### ISSUE TITLE
Crafting Keys (Key Fragments)

### ISSUE THREAD

**Issue by WispenGit** [Hazebyte/CrateReloaded#43]
Suggested this before via spigot message, however I think this is the more correct place to suggest it.

I personally use keys (as do many other servers) mainly as a purchase from my store via real money.

This cuts off a lot of people from getting access to being able to use keys, and for my setup giving entire keys out to players for completing tasks in-game would be a bit overpowered (unless the "task" in question was extremely difficult). 

However giving out a "Key Fragment" that could be used to later craft keys when you have gained multiple fragments would work great

So my suggestion is really just making keys craftable, the recipes could be custom.

This will allow for servers to let players gain keys slowly overtime instead of all at once, which makes it easier to give the fragments for less intensive challenges. 

Also as many servers have multiple tiers to there crate keys (common -> rare). This could allow for configuration of combining multiple less valuable keys, for a more valuable one giving the players the opportunity to use there less common keys right away, or save up until they can craft a more valuable one!

No clue how this would work in the coding or the config, but hopefully it's possible!

**Comment by BiGUNMAN** [comment]
I'd like to add to this feature request. Key fragments could be made into a command which would open sort of like a "Menu Crate", and so once you collected all the fragments the menu system would not only show you how much fragments you've collected, but also after that give you the completed key, or (upon config option) automatically start the Roulette menu or give you the reward by redeeming it via the menu.
