### ISSUE TITLE
NoSuchMethodException: org.bukkit.inventory.meta.ItemMeta.setCustomModelData

### ISSUE THREAD

**Issue by FrozenBeard** [Hazebyte/CrateReloaded#433]
Paper 1.12.2 updated to the latest CrateReloaded gives me this error on boot.

https://gist.github.com/FrozenBeard/46c4f44479bd9dc121bc22193b84dd4b

**Comment by imWillX** [comment]
Please DM me your crate.yml.

**Comment by imWillX** [comment]
Closing -- Duplicate.
