### ISSUE TITLE
Issue with spam clicking the crate

### ISSUE THREAD

**Issue by maxlehot1234** [Hazebyte/CrateReloaded#437]
Hi will,

I setup enderchest as physical crates on ym server and when players spam click it, it open the enderchest at the end. Quite weird and useless :)

If you can fix this, it could be really cool, since all of my players report this to me a lot of time.

I post it here, since you can't keep track of everything on Discord, since I already report this in november too ;) I know youmplan new things like release the source code, but in the meantime, a fix will be cool ;)

Thanks again will.

**Comment by imWillX** [comment]
This is really odd. I am unable to reproduce the issue but perhaps another plugin is interfering. Can you provide a plugin list?

**Comment by maxlehot1234** [comment]
@imWillX Here it is:
![image](https://user-images.githubusercontent.com/5159244/74890004-b953fe00-5350-11ea-80c4-28adb6cf87ab.png)
The 3 I hide are custom plugins and do not touch anything to enderchest.

**Comment by johncsuti** [comment]
Can confirm this happens randomly and it happens when there are no other plugins.

**Comment by johncsuti** [comment]
One of my staff had mentioned that if you use an auto clicker you can force it to happen a lot more.

**Comment by imWillX** [comment]
We had some throttling that ignored events from players if they click within 0.1s. 

You can disable this 
```
throttle:
  enabled: false
```
