### ISSUE TITLE
Custom Head Skull error using v2.0.21 - paper spigot 1.15.1

### ISSUE THREAD

**Issue by BobbyMere** [Hazebyte/CrateReloaded#438]
Got this error https://pastebin.com/z6dB5huy using this line ` - chance:(1.0), item:(player_head 1 name:&aWilltella lore:&aA_delicious_snack!! skull:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTE1ZGNiMmRhMDJjZjczNDgyOWUxZTI3M2UzMDI1NjE3ZDgwNzE1MTZmOTUzMjUxYjUyNTQ1ZGE4ZDNlOGRiOCJ9fX0)`

copied from wiki https://crates.hazebyte.com/#/config/crate using v2.0.21 on paper spigot 1.15.1.

This error doesn't show up when using v2.0.11 on paper spigot 1.13.2. I also only shows up if the 'skull:' is added
<img width="285" alt="h" src="https://user-images.githubusercontent.com/25316276/72764968-d8276f00-3baf-11ea-83b1-ad2d336123d5.png">
<img width="502" alt="l" src="https://user-images.githubusercontent.com/25316276/72764974-dd84b980-3baf-11ea-9ea9-890f23c37173.png">
<img width="170" alt="g" src="https://user-images.githubusercontent.com/25316276/72764975-df4e7d00-3baf-11ea-8f05-f21a69bf0f18.png">

**Comment by imWillX** [comment]
Fixed in `2.0.22`
