### ISSUE TITLE
[Request] Support item name in the 'display' part in Config.

### ISSUE THREAD

**Issue by geumu** [Hazebyte/CrateReloaded#447]
**Bukkit**: 1.12.2
**Plugin**: Crate Reloaded Pro 2.0.23
**Explanation**: In the crate.yml, I would like to add a function to support the 'display' part as well as the item name.

**Example**:

rewards:            
    - 'chance:(1), display:(**368** 1 name:Test lore:Test_Lore, cmd:(/cmi give money {player} 100)'

->

rewards:            
    - 'chance:(1), display:(**COAL** 1 name:Test lore:Test_Lore, cmd:(/cmi give money {player} 100)'

**Comment by imWillX** [comment]
Using the item name is the default way to do this. The ids were kept as a way to maintain backward compatibility.

**Comment by geumu** [comment]
Surely that would be a problem for us. This is because crate reloaded will have to be compatible with multiple versions.

So I'm going to suggest one idea.

Surely that would be a problem for us. This is because crate reloaded will have to be compatible with multiple versions.

So I'm going to suggest one idea.

**Image**: https://imgur.com/LsAKGZ7

It is to add '**custom_item_code.yml**' function to crate reload.

If you use custom_item_code: true in '**config.yml**'

The item code is imported from **'custom_item_code.yml**'. If you need it, I will create custom_item_code.yml for each version.

I wish this feature was added.

**Comment by geumu** [comment]
> Using the item name is the default way to do this. The ids were kept as a way to maintain backward compatibility.

Surely that would be a problem for us. This is because crate reloaded will have to be compatible with multiple versions.

So I'm going to suggest one idea.

Surely that would be a problem for us. This is because crate reloaded will have to be compatible with multiple versions.

So I'm going to suggest one idea.
　
　
Image: https://imgur.com/LsAKGZ7
　
　
It is to add 'custom_item_code.yml' function to crate reload.

If you use custom_item_code: true in 'config.yml'

The item code is imported from 'custom_item_code.yml'. If you need it, I will create custom_item_code.yml for each version.

I wish this feature was added.

**Comment by imWillX** [comment]
I’m not sure if I understand correctly. CrateReloaded is compatible with multiple versions. Custom item codes, the way you suggested, aren’t compatible with multiple versions because it needs to support data as wel.

**Comment by geumu** [comment]
i can make for you like this, for each version

custom_item_code_1_8.yml
custom_item_code_1_12.yml
custom_item_code_1_13.yml
custom_item_code_1_14.yml
custom_item_code_1_15.yml

i just want to crate support mod item...
