### ISSUE TITLE
Noteblock sound plays  twice when I open a crate

### ISSUE THREAD

**Issue by Tobi-Jakka** [Hazebyte/CrateReloaded#449]
Paper version 1.13.2 Build - 655

CrateReloaded PRO: Idk, /cr version does not return the version. But going by the date I added it I'd assume I use version 2.0.21

Issue:
Whenever I open a crate a noteblock sound plays twice.
I use key crates. This only happens when I click on a key crate with a key to open it.
I have checked my crates.yml & there are no soundeffects added to the crates.

Thanks in advanced

Edit: Seems this is a duplicate of #443

**Comment by imWillX** [comment]
Closing: Duplicate
