### ISSUE TITLE
Suggestions; Percentage & Multiple Rewards

### ISSUE THREAD

**Issue by PetKCH** [Hazebyte/CrateReloaded#45]
Instead of only showing chances rounded, add variblae to show it with 1 or two decimals.
(Need because some of my items are set to like 0.5 chances and it shows them as 0%)

Ability to control chance of giving multiple rewards. I would like to have come variable with which I could control what are the odds of player getting more than one reward.

**Comment by imWillX** [comment]
Hey Laos1996,

We currently have a decimal format in the config.yml. Please use that to set the amount of decimals.

How would you like to control the odds?

**Comment by Laos1996** [comment]
To control odds, it could be permission + config based (For example, "modify by yourself probabily of winning 2nd, 3rd item) and then another permission which increases the chances (Can be a donator perk that way). Even tho already option to configure probability of winning would be fine by me. (I have no idea how to make it in config so it would be simple to use tho, maybe something like #Define ammount of chances to win per tier, like Chance-2:25%, Chance-3:10% Chance-4:5%. Still by this idea, it would have to be first it scrambles for chance-2, if player wins it, then it goes to scramble for chance-3, if it wins, goes further, if not, gives that ammount of random items)

I really complicated it now haven't I? :P
