### ISSUE TITLE
CS:GO crate animation not ending properly

### ISSUE THREAD

**Issue by Tobi-Jakka** [Hazebyte/CrateReloaded#450]
Paper version 1.13.2 Build - 655

CrateReloaded PRO: Idk, /cr version does not return the version. But going by the date I added it I'd assume I use version 2.0.21

Issue:
So I have "peri-exit: true" in my config file.

Though I think it's weird that when you exit a crate you still have to wait for it to finish. Would be nice if you could make the crate instantly finish when you exit (not like you get the item you were on, but I suppose it have some sort of idea what item you are going to get before the animation even starts).

Its a bit weird not being able to open another CS:GO crate before previous thing is done when you can't even see it nor get your item.

Thanks in advanced

**Comment by imWillX** [comment]
Due to how our animations are built at the moment, I won't be implementing this. 

This may be implemented in the future in an animation update.
