### ISSUE TITLE
PlaceholderAPI varaibles or CMI Hologram support

### ISSUE THREAD

**Issue by FrozenBeard** [Hazebyte/CrateReloaded#451]
Ahoy

I see you support Holograms plugin, but not CMI Holograms, which is the second largest hologram plugin for Spigot servers, if you created a placeholderAPI plugin then I could just add this to any existing plugin like CMI Holograms and put them above crates to show crate information above the crates.
Otherwise, could you please suppose CMI Holograms as they have an API, as I dont want to have to use 2 separate hologram plugins just to get Crate holograms working.

You could have a Hologram actually spin the items that are in a crate, so others can see when a user opens a crate and its spinning as Holograms can show items in them, with an awesome winning Hologram animation to show what they won.

Via https://github.com/Hazebyte/CrateReloadedAPI/issues/43

**Comment by FrozenBeard** [comment]
Bump, can you please add CMI support.

**Comment by imWillX** [comment]
Just an update on this. I can get HD working on CrateReloaded but it won't be perfect like HolographicDisplay. 

The CMI API is outdated and functionality that's in the API is not in the actual jar.

**Comment by imWillX** [comment]
Just an update on this. I can get hologram working on CrateReloaded but it won't be perfect like HolographicDisplay nor will I extend this functionality out in the future. It'll just be base text which is what we support now. The reason for this is that the CMI API is outdated and it doesn't reference the actual plugin that well.

**Comment by imWillX** [comment]
Added, will be released in `2.0.31`. Enjoy.

**Comment by TomLewis** [comment]
> 
> 
> Just an update on this. I can get hologram working on CrateReloaded but it won't be perfect like HolographicDisplay nor will I extend this functionality out in the future. It'll just be base text which is what we support now. The reason for this is that the CMI API is outdated and it doesn't reference the actual plugin that well.

ok! Maybe make a ticket about his API, his docs are horrendous he never updates them but hes always adding features and changing his API etc but he does reply! so worth making a ticket!

**Comment by TomLewis** [comment]
Doesn't seem to work.
Added
```
  holographic:
      - '&7[&aSpring Treasure Chest 2021&7]'
```

In my crate, nothing.

**Comment by imWillX** [comment]
CMI isn’t enabled by default. Please take a look at the config for the holographic-plugin key and set it to CMI.

**Comment by TomLewis** [comment]
Thanks this worked!
