### ISSUE TITLE
Crates Rewards not given - Throws Console Error

### ISSUE THREAD

**Issue by OmegaWeaponDev** [Hazebyte/CrateReloaded#453]
Hi,

With CratesReloaded v2.0.23, we currently have the rewards setup like: https://i.imgur.com/CUIc1m4.png But for some reason when a player tries to open a crate with the correct key nothing happens in-game and the we get the following Error in console: https://hastebin.com/olaruriyak.sql

Players have been advised to save the keys for now as if they try in-game to use the crate it takes the key but no rewards are given and the above error happens.

**Comment by OmegaWeaponDev** [comment]
We have tried to re-create the crate as well, and it did not resolve the issue. Wanting to get this fixed asap.

**Comment by imWillX** [comment]
Config error. Please check console to ensure the crate is setup correctly.
