### ISSUE TITLE
Unable to open crates on 2.0.24 and 2.0.25 ( works on 2.0.23 )

### ISSUE THREAD

**Issue by AmazedMender16** [Hazebyte/CrateReloaded#457]
Ever since upgrading to 2.0.24/2.0.25 my users are getting black/gray smoke when they try to open the crates ( chest ), this is working perfectly fine on 2.0.23.

The users are not getting any feedback from the crates, they do when they click on random other blocks.

https://prnt.sc/sdna5m

**Comment by imWillX** [comment]
User error: likely spawn protection or world guard flags were not set.
