### ISSUE TITLE
WorldGuard chest-access flag prevents opening crates on latest.

### ISSUE THREAD

**Issue by nolky** [Hazebyte/CrateReloaded#458]
On versions 2.0.26, 2.0.25, and 2.0.24, the WorldGuard flag 'chest-access' prevents users from using a key or interacting with the crate whatsoever, I tested this on version 2.0.23 and I did not run into this issue. I'm pretty sure it was with the PlayerInteractEvent changes on version 2.0.24, I could be wrong though.

This only applies to crates that are chests or any other type of container.

**Comment by imWillX** [comment]
Hey,

Could you try adding in the interact flag to the specific crate area?

**Comment by nolky** [comment]
I created a child region to my spawn region and allowing chest-access in the child region worked.

**Comment by imWillX** [comment]
I’m assuming that solved the issue. May I close this issue then?

**Comment by nolky** [comment]
Yes, the issue is solved, I just believe there shouldn't have to be a workaround to solve the issue.

**Comment by imWillX** [comment]
Great, it was previously incorrect behavior. Specifically, we shouldn’t be ignoring protection plugins. This isn’t necessarily a workaround but correct behavior.
