### ISSUE TITLE
Crates not loading

### ISSUE THREAD

**Issue by SlimeCody** [Hazebyte/CrateReloaded#460]
'cmd:(/cmi head CodyOfCactus {player} 1), chance: (1), display:(player_head 1 name:&1CodyOfCactus player:CodyOfCactus), msg:(&cServer &f&1» &fYou have received &1&lCodyOfCactus&fs head!)'

![image](https://user-images.githubusercontent.com/49579480/82718794-5c772500-9c6a-11ea-9171-743f8e3ec7ee.png)

it displays in preview perfectly fine when I do /cr preview Collector

**Comment by imWillX** [comment]
Please provide the full crate yml.

**Comment by ProfCube** [comment]
@SlimeCody here is a bit of a fix towards the crate.yml section 

`unique:(),     chance:(1),          cmd:(cmi head CodyOfCactus {player} 1), chance: (1),   display:(player_head 1 skull:&1CodyOfCactus name:CodyOfCactus), msg:(&cServer &f&1» &fYou have received &1&lCodyOfCactus&fs head!)`

![Capture](https://user-images.githubusercontent.com/30348072/82719426-80d9fe00-9c78-11ea-952b-3b77af22bdb3.PNG)

**Comment by SlimeCody** [comment]
ProfCube helped me resolve this on Discord, thanks again!
