### ISSUE TITLE
Crate Keys in Item Frames

### ISSUE THREAD

**Issue by IPv5** [Hazebyte/CrateReloaded#465]
Hello there, I am writing an enhancement request. I am looking to be able to toggle the ability to put CrateKeys into Item frames. Currently, when trying to do so you get an error saying you can't put this item in an item frame. This would be used for player shops as players like to be able to provide the item for sale in the item frame and attract more customers. 
Thank you!

**Comment by imWillX** [comment]
This toggle has been added. It'll be released in 2.0.29.
