### ISSUE TITLE
Crate Reloaded Animations Error

### ISSUE THREAD

**Issue by ZEROOblivious** [Hazebyte/CrateReloaded#466]
Paper 1_15_R1
Plugin Version: 2.0.27

Error Code on whenever using Animations, you still get the reward but the animations are not working in the most recent update of Crates Reloaded for 1.16 Support.

https://pastebin.com/DdnnLGqF

**Comment by imWillX** [comment]
Fixed in 2.0.28.

Thanks for testing.
