### ISSUE TITLE
Crates Reloaded [FREE] Version Error While Startup and while doing /cr reload

### ISSUE THREAD

**Issue by YTMrSnipa** [Hazebyte/CrateReloaded#468]
Startup Error 
https://pastebin.com/PYaVxZeZ

/cr reload Error:
https://pastebin.com/i6f0XZUS

Oh and this error while getting a key:
https://pastebin.com/pAjw5f8M

I am using Paper 1.16.1 
And Latest version of crates reloaded Free

**Comment by imWillX** [comment]
Will use #469 as reference.
