### ISSUE TITLE
[Question] How do you set a "Text" class on a crate?

### ISSUE THREAD

**Issue by Tomi010817** [Hazebyte/CrateReloaded#473]
So I wanted to set a "Text" class inside of one of my crates, to run inmediately after opening the crate. The thing is that I haven't seen any place on the wiki explaining on how to use it or how to set the text that you want to display. I asked 3 times on discord but I haven't received any reply (I guess because no one actually knew). Would be very happy if I can get a response on how to use this class and even more happy if you could add the explanation to the wiki page. Cheers!

**Comment by imWillX** [comment]
I haven't tried this out but does it show anything at all?

**Comment by Tomi010817** [comment]
Hello!
And nope, I really don't know how to set it up as a class, there is a guide for fireworks for example, but I don't nothing related on how to set up the Text class and how the node where the text goes should be named.

**Comment by imWillX** [comment]
Give this a shot. I tested it ingame so it should work. Please reopen if you have any more questions.

```
        text-example:
          class: Text
          text: 'Heya Friend'
          category: PERSISTENT
```

**Comment by Tomi010817** [comment]
Thanks a lot Will! You are the best, hope you have a great day

**Comment by Tomi010817** [comment]
I've tested it but nothing shows up, the Class isn't taken, I also tried the exact example you gave but didn't work. I'm using the lastest version from the free version of this plugin on an environment of Spigot 1.8.8

**Comment by Tomi010817** [comment]
If you need I can test it on an empty local host, but I'm pretty sure it isn't caused by any other plugin. Also no console errors are shown

**Comment by imWillX** [comment]
@Tomi010817 Sorry, our effects don't work in 1.8.8 anymore.

**Comment by Tomi010817** [comment]
Oh I didn't know this included the Text class. I wanted to display a text when someone opened a crate in a broadcast way, like "{p} has opened the legendary crate!" but that way seem to be the only one, tho you can broadcast things but from what I know, you can only do it at the END (with this I'm meaning when the player finishes claiming his reward on the crate)

**Comment by Tomi010817** [comment]
The thing is that I was looking for a form to broadcast it when the player opens it

**Comment by imWillX** [comment]
Anything under the effect column won’t be supported in 1.8. We have a message column specifically for this.

**Comment by Tomi010817** [comment]
Yeah, I partially knew that until now, I use a plugin called BlockParticles for giving Particle effects to my crates, tho on my last message I was meaning if there was a way to broadcast a message when opening a crate at the start and not at the end, this on the **message** column.
