### ISSUE TITLE
Enchanted Shields don't come out enchanted

### ISSUE THREAD

**Issue by Braynblocks** [Hazebyte/CrateReloaded#474]
I have added several enchanted stuffs to my crates, one of which is a shield. Every entry has the same format and every entry came out enchanted -- except shields.

**Comment by TheRBZ** [comment]
I am also having this issue, can confirm. Using 2.0.29

**Comment by TheRBZ** [comment]
I am also having this issue, can confirm. Using 2.0.29

**Comment by imWillX** [comment]
Fix `2.0.30`
