### ISSUE TITLE
Dupes

### ISSUE THREAD

**Issue by YTMrSnipa** [Hazebyte/CrateReloaded#475]
So some players from my server figured out if you quickly shift-click the item (moving it to your inv) and close the menu at the same time, the item stays in your inventory.

Link to video:
https://drive.google.com/file/d/14uEnOXN0tHVp7myNkbyUAg_NmwvmmuHI/view?usp=sharing

https://drive.google.com/file/d/1t-ov7R8eFbWvLQ35cReuSuSIvFS82sI0/view?usp=sharing

https://drive.google.com/file/d/1Ehx_26Q2KOYhFmfNjm77mag3q6XVdFVZ/view?usp=sharing

PLEASE FIX ASAP.

**Comment by imWillX** [comment]
This is because of another plugin cancelling our plugin's action

We had this report several times.
