### ISSUE TITLE
Null Display Objects.

### ISSUE THREAD

**Issue by SlimeCody** [Hazebyte/CrateReloaded#476]
![image](https://user-images.githubusercontent.com/49579480/88503303-ec9d5780-cf96-11ea-8180-1ca9da9d13c4.png)
Requested by Will to make this. 

Null Display Objeccts, messing up the ability to claim, crates.

**Comment by imWillX** [comment]
This was a result of using our 1.8-1.15 material name normalizer. Rewards that were unable to be saved should now be displaying correctly. Fixed in `2.0.31`.
