### ISSUE TITLE
Double Click on Enderchest

### ISSUE THREAD

**Issue by DjeyMute** [Hazebyte/CrateReloaded#478]
Hi,
When you double click on the enderchest, the enderchest open your ender inventory.
Do you have any solution for this ?

**Comment by SMASH8530** [comment]
I personally just use this code in skript to deny the echest opening:
on right click on ender chest:
	if "%region at event-player%" contains "REGIONNAME":
		cancel event

**Comment by DjeyMute** [comment]
But I'm not a developper. ^^'

**Comment by SMASH8530** [comment]
Just copy paste the code if you have skript?

**Comment by DjeyMute** [comment]
I don't have skript only java.

**Comment by imWillX** [comment]
You can disable this via the config. 
```
throttle:
  enabled: false
  speed: 200
```

**Comment by DjeyMute** [comment]
Where ? ^^ I don't see this in the config. :x
