### ISSUE TITLE
RGB Support

### ISSUE THREAD

**Issue by Sikatsu** [Hazebyte/CrateReloaded#481]
It would be nice if you can add RGB support to CrateReloaded. I can provide some code examples that might help with this. ^^

https://pastebin.com/SfAhybZD
https://pastebin.com/Ks3J4tu5

This uses the {#RRGGBB} format that many other plugins use.

**Comment by mibby** [comment]
CrateReloaded 2.0.30.1
Paper dev 158 (Spigot 1.16.2)

@imWillX This is what ends up appearing if you use %vault_prefix% placeholder before {player}.

```
core.claim_hold = {p} &lHey %vault_prefix%&l{player}&7&l! &7You have &c{number} pending rewards&7. Type &e&l/claim &7to get them!
```
![link](https://i.imgur.com/0TKH2oX.png)

{player-name} properly parses their HEX color, but then I can't bold the player name in the message. So some form of interpretation may be needed.

**Comment by imWillX** [comment]
Thanks all, this will be added in `2.0.33`.
