### ISSUE TITLE
Crate Keys can be eaten / used

### ISSUE THREAD

**Issue by TheRBZ** [Hazebyte/CrateReloaded#482]
**MC:** 1.16.1
**Paper Build:** 133
**CrateReloaded ver:** 2.0.30

When using crate type KEYCRATE and the crate key item is a piece of food or a usable item such as an eye of ender, they can be used and will disappear.

For example:
```
Basic:
    type: KEYCRATE
    item: 'potato 1 name:&e&lBasic_Token lore:&7Type_&8»_&e&lBASIC|&7Use_at_&8»_&f/warp_tokens'
```

**Comment by imWillX** [comment]
I'm testing this and i'm unable to reproduce this. This may be caused by another plugin improperly undoing our task cancellation. Please reopen if this persists.
