### ISSUE TITLE
1.16.2 GREEN & RED DYE Issue

### ISSUE THREAD

**Issue by BobbyMere** [Hazebyte/CrateReloaded#484]
Using paper spigot 1.16.2 with cratesreloadedpro  v2.0.30

Both GREEN_DYE and RED_DYE get this error when holding the item and doing /cr util item 
https://hasteb.in/gupodove.swift
https://hasteb.in/orohupey.lua

**Comment by imWillX** [comment]
The hastebins have expired. Could you relink them?

**Comment by imWillX** [comment]
Closing, no response.
