### ISSUE TITLE
[2.0.23 FREE] Server freeze when trying to preview a crate with many skulls

### ISSUE THREAD

**Issue by iGabyTM** [Hazebyte/CrateReloaded#488]
Server version: `Tuinity version git-Tuinity-"4513d90" (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)`
Crate: [link](https://paste.helpch.at/ugelusequr.yaml)

**Comment by imWillX** [comment]
Recommendation from discord: Use the texture data instead of skull name lookup.
