### ISSUE TITLE
2.0.31.1 broke all keys from working at all & created a cooldown.

### ISSUE THREAD

**Issue by TomLewis** [Hazebyte/CrateReloaded#489]
Paper 1.12.2, using the latest 2.0.31.1, I upgraded from 2.0.30.1.

Fully broke all keys from working, when peolpe spam the key into the chest to get it to work it does nothing, then spamming gives a cooldown.

See the bug report & video on https://github.com/PirateCraft/dev/issues/47

**Comment by imWillX** [comment]
Should be fixed in the latest patch.
