### ISSUE TITLE
(Premium v2.0.32) Hologram Modifier setting not work anymore

### ISSUE THREAD

**Issue by JokerLiuPro** [Hazebyte/CrateReloaded#490]
CrateReloaded v2.0.32 (Premium)
Paper: 1.16.3 #202 
Holographic Displays v2.4.4

Latest version ignore the Hologram Modifier setting in config

v2.0.32
https://cdn.discordapp.com/attachments/343284899010052106/757239362051113000/unknown.png

v2.0.30 (normal)
https://cdn.discordapp.com/attachments/343284899010052106/757239340148588554/unknown.png

**Comment by Tyloon1e** [comment]
Experiencing same issue.

**Comment by imWillX** [comment]
@Tyloon1e @JokerLiuPro Fix will be released in `2.0.33`
