### ISSUE TITLE
soundVolume not applied

### ISSUE THREAD

**Issue by Tyloon1e** [Hazebyte/CrateReloaded#492]
When adding a sound like so:
`        2:
          class: Sound
          category: INSPECT
          sound: BLOCK_CHEST_OPEN
          soundVolume: 50`
It doesn't matter what I set soundVolume to. The sound is still the same level - even after a server restart.

**Comment by Tyloon1e** [comment]
Any update on this?

**Comment by imWillX** [comment]
@Tyloon1e Thanks for the bump. I'll be testing this today.

**Comment by imWillX** [comment]
@Tyloon1e It seems that this option may be broken. I could try manually compiling a version for you with a new default sound. Does this sound alright?

**Comment by imWillX** [comment]
@Tyloon1e It seems that this option may be broken. I could try manually compiling a version for you with a new default sound. Does this sound alright? a

**Comment by imWillX** [comment]
@Tyloon1e It seems that this option may be broken. I could try manually compiling a version for you with a new default sound. Does this sound alright? a

**Comment by Tyloon1e** [comment]
@imWillX Sure

**Comment by Tyloon1e** [comment]
Issue persists.

**Comment by imWillX** [comment]
I’ll upload a fix today and provide you a new jar.
