### ISSUE TITLE
Claim Issue

### ISSUE THREAD

**Issue by Nezz202** [Hazebyte/CrateReloaded#493]
Hey,

Issue re-posted from [Discord](https://discordapp.com/channels/158426155471339520/689933767225507854/756135448052498442).

Plugin Version: 2.0.32
Paper Spigot: 1.16.3-231

Configuration Setting: 
```
  # If the inventory is full, let the claim manager handle it.
  # Otherwise, it will drop to the ground.
  handle-full-inventory: false
```

Issue:
Have a crate that gives 4 items when you open it.
When I open the crate with 4 free inventory slots, I get all 4 items. This is fine.

If I open the crate with 3, 2 or 1 free inventory slots, I get enough items to fill my inventory, and the rest goes into the claim gui, which as per the setting above, I don't wish to use.

If I have no inventory space, the key doesn't work. This is also correct

Please let me know if you need any more information.

Thanks :)

**Comment by imWillX** [comment]
Thanks for the report. This is fixed in `2.0.33`.
