### ISSUE TITLE
always:() doesn't work

### ISSUE THREAD

**Issue by Sikatsu** [Hazebyte/CrateReloaded#494]
Copied this from the official website and added a display. Can't get it to work. It never triggers even tho it should always trigger.

    reward:
        minimumRewards: 1
        maximumRewards: 1
        rewards:
            - 'always:(),                          cmd:(/cmi heal {player}), display:(TOTEM_OF_UNDYING 1 name:&3Altijd_Genezen glow:true lore:|&7Word_genezen_iedere_keer|&7als_je_de_kist_opent.||&6Kans:_100%)'

**Comment by BobbyMere** [comment]
so for this to work, you need an additional item. Always is redundant when there's only one items.
