### ISSUE TITLE
CrateReloaded resets hologram.yml from CMI

### ISSUE THREAD

**Issue by Sikatsu** [Hazebyte/CrateReloaded#498]
After installing the latest update and restarting the server, it completely reset the hologram.yml file from CMI.

**Comment by LogGits** [comment]
How do you know it's CrateReloaded doing this (e.g. any errors)? Also please provide CMI version, Server version, and CrateReloaded version.

I experienced my CMI holograms.yml file reset aswell, so just want to be sure.

**Comment by Sikatsu** [comment]
No errors, the bug has been confirmed by Will.

**Comment by imWillX** [comment]
Fixed via a silent update on spigot. Please update if this affects you.
