### ISSUE TITLE
[Suggestion] Shift-Animation

### ISSUE THREAD

**Issue by Pandas0** [Hazebyte/CrateReloaded#514]
Just like the animation and end-animation settings, I feel like a shift-animation setting would be a nice feature to have. I have had many people suggest to me for a way to skip the animation when shift opening a crate key, I would love to add this feature, but I don't think it's possible within the plugin currently without disabling the animation completely and not just when a player is shifting.

**Comment by imWillX** [comment]
There is a feature that allows you to exit an animation mid-way (peri-exit). If there is enough support for a feature like this, I would consider adding in an add-on but not necessarily to the main plugin.

**Comment by Pandas0** [comment]
Yeah, I already have peri-exit enabled on my server but it still requires them to wait for the animation to complete for the reward. I think there main thing was opening a lot of keys quickly instead of having to wait for the animation delay, but I didn't want to just remove the animation for players that only have a few keys to open.
