### ISSUE TITLE
[Request] Check free inventory slots

### ISSUE THREAD

**Issue by Artuto** [Hazebyte/CrateReloaded#515]
Please add a way to specify how many free inventory slots are needed for a given reward.

If the player has enough execute the reward, otherwise, warn the player and tell them to claim it.

**Comment by imWillX** [comment]
The plugin will automatically determine the number of free slots and attempt to give the player the set of items that can be fit in the inventory. Any item part of the same stack that is unable to be given will be put into the player's claim.

Target: `2.1.11`
