### ISSUE TITLE
[Bug] Creepers can blow up your crate chests..

### ISSUE THREAD

**Issue by Tobi-Jakka** [Hazebyte/CrateReloaded#519]
A creeper can blow up your crate chest... It will leave the hologram behind.

Though if you go & place a new chest manually it will allow you to access it again, but without replacing chest the /cr remove command doesnt seem to work

**Comment by imWillX** [comment]
The plugin intentionally leaves the protection of the crates to other plugins such as WorldGuard. We intend that the plugin provides Crate features while delegating the task of block protection to other specialized protection plugins.
