### ISSUE TITLE
[SUGGESTION] Quick reward collect.

### ISSUE THREAD

**Issue by Kesims** [Hazebyte/CrateReloaded#520]
Hello, would it be possible to implement some quick reward collecting? For example if the player SHIFT-clicked the chest, it would give him the reward instantly, instead of running animation. That would be useful for players, that have a lot of keys to collect rewards - now it takes a lot of time to wait every time for the animation to finish. 

Thanks for response! :)

**Comment by BobbyMere** [comment]
Are you referring to /cr claim? this would already be a thing. Also, there's /cr claimall even though it's not listed anywhere

**Comment by Kesims** [comment]
No no, I mean the opening of the chest with key. You click the chest with key and than you have to vait until animation finishes to get the reward. So I thought it would be cool, if player could somehow skip the animation and get the reward instantly after clicking the chest.

**Comment by BobbyMere** [comment]
There's an option for this in the config 
```  # Length of CSGO animation
  csgo: 6

  # Length of roulette animation
  roulette: 5

  # Length of wheel animation
  wheel: 8

**Comment by Tomi010817** [comment]
I like the suggestion, it sounds pretty cool.
@BobbyMere He wasn't asking for a way to disable animations duration. He just wanted a way for players to skip the animations (only if they wanted) by SHIFT clicking the chest so it would skip the animation for those who don't like to wait until every animation finishes, tho the animation would still be there if the player opens the crate with a normal click.
 This should be an optional setting in the `crates.yml` so you can enable the SHIFT + RIGHT-CLICK animation skip feature for specific crates and not all of them. Maybe some server owners don't want people to be able to skip the animations on certain crates.

**Comment by imWillX** [comment]
Included ability to exit animation
