### ISSUE TITLE
[Bug] Crate Titles Replicate Key Lore

### ISSUE THREAD

**Issue by ArcticRaven** [Hazebyte/CrateReloaded#541]
When pushing Key item lore to a 2'nd line - the lore then appears under the title of the crate. 

So this configuration with no space between key name and the lore is fine
`item: 'TRIPWIRE_HOOK 1 name:#ccccccExampleKey lore:#fab40bExample_Key_Lore glow:true'`

However in this configuration, you should see "Example Key Lore" appear under the title of the crate
`item: 'TRIPWIRE_HOOK 1 name:#ccccccExampleKey lore:|#fab40bExample_Key_Lore glow:true'`

**Comment by iGabyTM** [comment]
Try to add a color code before the `|`.

**Comment by ArcticRaven** [comment]
Same result. The 2nd line of lore still appears below the title of the crates.
