### ISSUE TITLE
Animations throwing console errors and not working 2.0.36

### ISSUE THREAD

**Issue by TomLewis** [Hazebyte/CrateReloaded#551]
https://gist.github.com/TomLewis/e61605877622bfb090a0be34e70116ba

Annimations not working & throwing exceptions in the log, also did you forget to update the internal version? its reporting 2.0.35 in-game when I downloaded and am using 2.0.36.

Paper 1.18.1
Crate Reloaded Pro 2.0.36

**Comment by imWillX** [comment]
Fixed in 2.0.37.
