### ISSUE TITLE
Crate "key" items duplicate Slimefun "head" items when using to mine them.

### ISSUE THREAD

**Issue by mrcoffee1026** [Hazebyte/CrateReloaded#553]
Also sporadically duplicates Slimefun vanilla-style blocks with lore: drops vanilla version of item while leaving original in tact.  Haven't been able to duplicate with other plugins (so far).

Please see for additional details:
Github ticket submitted to Slimefun about same issue: https://github.com/Slimefun/Slimefun4/issues/3574

Testing the "key" item on Slimefun head items, Slimefun vanilla block items and a couple of other plugin items:  Could only find issues with Slimefun items so it is probably related to that plugin in some way.  Slimefun items should not be able to be mined without a proper "tool" so unless you've somehow identified the key items as a proper Slimefun "tool" I'm not sure how to resolve this:
https://vimeo.com/709927942?embedded=true&source=vimeo_logo&owner=99159429

**Comment by scottyboii** [comment]
Fixed as of CrateReloaded pro 2.1.13, fix on free coming soon
