### ISSUE TITLE
NBT Tags parsing incorrectly applying quotation marks.

### ISSUE THREAD

**Issue by RequaUK** [Hazebyte/CrateReloaded#557]
Version: 2.0.34

The following display item should have the NBT tag(s) within ``{}``
``display:(pixelmon_pixelmon_sprite{ndex:1s,form:"",gender:0b,palette:"none"} 1)``

However this is the outcome:
![myM8poD](https://user-images.githubusercontent.com/88196620/179361983-00303458-4968-4d3d-9315-76137c74db16.png)

As you can see the values for ``ndex`` and ``gender`` are surrounded in quotation marks. Which causes an incorrect sprite to appear.

How it _should_ look:

![pas7mq2](https://user-images.githubusercontent.com/88196620/179362026-9d201bad-152a-4bf8-8b10-10dedcf04dbb.png)

My suggestion is take the literal values and not wrap them in quotationmarks.

**Comment by zThana** [comment]
https://crate.hazebyte.com/docs/faq#what-is-the-difference-between-the-free-and-premium-version
![image](https://user-images.githubusercontent.com/8803519/212572658-d7868f38-f8a9-43e8-9a93-ccf3c99d35e5.png)

Can't test NBT not attempt to reproduce this issue. When can we expect NBT to be usable again?

**Comment by zThana** [comment]
Just got updated on Spigot. NBT works again as per v2.1.15
