### ISSUE TITLE
[Feature] Even less key item security

### ISSUE THREAD

**Issue by UltraFaceguy** [Hazebyte/CrateReloaded#558]
I'm looking to make keys work for only a material and customModelData match, ignoring name, lore, and all other details. As far as I can tell, the current comparison settings don't allow for this. My proposed solution is a configuration value that makes key matching "only defined", so if I define `item: "tripwire_hook{CustomModelData:250} 1"` it will only care about the quantity material and model data. If I included the name to be anything at all, it would require a match, but with no name specified, no name match is required.

Thanks

**Comment by imWillX** [comment]
Related: #562

**Comment by imWillX** [comment]
Tracking in #562
