### ISSUE TITLE
/cr util export & /cr util item not generating code for heads

### ISSUE THREAD

**Issue by TomLewis** [Hazebyte/CrateReloaded#560]
When using `/cr util export` or `/cr util item` on a custom head, the head data is not generated.
It straight up does not generate the `skull:` code any more.

20.0.39
purpur 1.18.2

**Comment by imWillX** [comment]
@TomLewis Thanks for the report. To narrow down this issue, is this a regression that recently occurred or has this never generated head data?

**Comment by TomLewis** [comment]
this never used to be a problem, so at some point its been broken. I cant sadly tell you when, as I only just noticed.

**Comment by imWillX** [comment]
Will be fixed in the next patch on spigot.
