### ISSUE TITLE
Invalid Username Support with GeyserMC

### ISSUE THREAD

**Issue by DoubleYouCash** [Hazebyte/CrateReloaded#578]
Hello, I have bedrock account support on my server with GeyserMC, which adds a prefix * to the username of the player who is connected through geyser. This means that they aren't able to receive any crate keys because the plugin rejects their username as invalid. Is there any possible way that prefix support could come to CrateReloaded? I am a premium user and I don't see support for this in the config anywhere, unless I missed it. Thanks!
![image](https://user-images.githubusercontent.com/12667378/200608337-d537f53d-95ba-44b9-ba81-3a823ac74542.png)

**Comment by imWillX** [comment]
This was fixed in 2.1.6.
