### ISSUE TITLE
handle-full-inventory not working as expected

### ISSUE THREAD

**Issue by CoolDCB** [Hazebyte/CrateReloaded#589]
Whilst using the `handle-full-inventory` config section I have noticed that no items drop. Both giving myself a crate key and opening one with a full inventory. 

Giving me one still went to claim and opening one with a full inventory the items just don't get given at all unfortunately

**Comment by imWillX** [comment]
Fix in 2.2.6

**Comment by CoolDCB** [comment]
Thank youu

**Comment by CoolDCB** [comment]
I've just tested this new version on our server and items still do not get dropped on the ground upon opening the crate

**Comment by CoolDCB** [comment]
This has now been fixed in 2.2.8
