### ISSUE TITLE
Updated from 2.2.5 to 2.2.9 and it broke all messages if you get keys or send out keys

### ISSUE THREAD

**Issue by TomLewis** [Hazebyte/CrateReloaded#590]
/crate give all <crate> 1, no longer sends messages when you do it, also the players do not get messages when they get given keys.

Every single update ive done breaks things.

I will be backdating to 2.2.5 for now.

**Comment by imWillX** [comment]
@TomLewis Taking a look.

**Comment by imWillX** [comment]
Fixed 2.2.30
