### ISSUE TITLE
I can't create custom armor in config (the armor trim implementation feature)

### ISSUE THREAD

**Issue by KM-Owner** [Hazebyte/CrateReloaded#591]
Server version (1.20 version)
CrateReloaded version (the latest)

The command /crate util export shows only "DIAMOND_CHESTPLATE" without template (the armor trim implementation feature in 1.20) :c

Screens below:
![image](https://github.com/Hazebyte/CrateReloaded/assets/122387923/db5da765-ab0c-488f-9cbc-898557d7377f)
![image](https://github.com/Hazebyte/CrateReloaded/assets/122387923/69676a1d-fe3f-44bc-bc81-5b5b0ec3dd16)
![image](https://github.com/Hazebyte/CrateReloaded/assets/122387923/e60b39fe-114d-449a-8ba6-b20f39c38c45)

**Comment by DjeyMute** [comment]
News ???

**Comment by imWillX** [comment]
Add serialization in 2.3.8
