### ISSUE TITLE
Issue can't parse command with # in it

### ISSUE THREAD

**Issue by TomLewis** [Hazebyte/CrateReloaded#594]
For some reason crate reloaded will not parse a cmd that includes a hash tag, escaping the character like \# makes the warning go away but the command does not run then, discord srv requires the hash in front of the channel ID, all I'm trying to do is log to discord via discord srv command but it won't run the command!

**Comment by imWillX** [comment]
@TomLewis Can you provide an example of the reward line?

**Comment by TomLewis** [comment]
`/discord broadcast #1111111111111111111 ✪✪✪✪ {player} opened Opened {crate} and won **{item}**`

**Comment by imWillX** [comment]
Fixed in 2.3.2. This was converting #111111 into a color
