### ISSUE TITLE
Don't open MYSTERYCRATE when dropping it

### ISSUE THREAD

**Issue by WarnDa** [Hazebyte/CrateReloaded#595]
Hello,

When you drop a MYSTERYCRATE using your drop key, it opens it.
But player complain because sometimes they just want to drop it to other player, and it opens the box :/

If you could add an option in config to disable this setting, and make the item drop like a vanilla item, would be perfect :)

**Comment by KneesDev** [comment]
It's not even safe to give another player a crate key by dropping it. Install a decent trade plugin to your server.

**Comment by WarnDa** [comment]
> It's not even safe to give another player a crate key by dropping it. Install a decent trade plugin to your server.

Skyblock server, players are on the same island, what is not safe lmao ?
I already got a trading plugin byt way longer
And sometimes players are just dropping their items and fail and it drops the crates, it directly open them.

**Comment by KneesDev** [comment]
Then your player can drop the key to the void and boom, it will never be seen again.

**Comment by imWillX** [comment]
Unable to reproduce - please reopen with more details or a gif.
