### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by WarnDa** [Hazebyte/CrateReloaded#598]
Hello,
Since the newest update, I can't translate anymore the lore into the /cr claim
For example I got this : 
![image](https://github.com/Hazebyte/CrateReloaded/assets/31826333/135a0048-70ac-4739-8752-e26cf45222be)
But in my config I got : 
![image](https://github.com/Hazebyte/CrateReloaded/assets/31826333/a28919c0-12bc-4f01-9bfc-d480c0136a1f)

Versions : 
![image](https://github.com/Hazebyte/CrateReloaded/assets/31826333/e6506e77-ab9b-48b1-859b-cdbf4a289401)

**Comment by imWillX** [comment]
Fixed in 2.3.8
