### ISSUE TITLE
Master Key - Feature Request

### ISSUE THREAD

**Issue by jasjmorris** [Hazebyte/CrateReloaded#60]
So I didn't see a way to do this with current configs/options.

I have multiple worlds, so when a user votes on a site, they are just going to get 1 key no matter what world they are in. I don't want the Vote Prize to be the same chance/types in all the worlds however.  

so is there a way that i can give a master key with the /vote so no matter what world they are in they can use the key for whatever world they are in?

**Comment by jasjmorris** [comment]
@imWillX Talking with some fellow staff on my server, I think maybe a master key would be handy, but is it possible we can have 1 key work for select crate , but not all cause we want to have a ultra rare chest, so to avoid the user just going to this crate with a master key we just want a key that we can have work for select crates

**Comment by imWillX** [comment]
Tracking #562
