### ISSUE TITLE
2.3.12 broken key colors

### ISSUE THREAD

**Issue by TomLewis** [Hazebyte/CrateReloaded#605]
Upgraded from CrateReloaded-2.2.5 to CrateReloaded_2.3.12_nbt and it just breaks keys.

This is suppose to be colored text.

![2024-06-14_21 56 06](https://github.com/Hazebyte/CrateReloaded/assets/144046/409ebe4f-3070-4295-a373-f3adfe3d1a9d)

Rolling back again to 2.2.5.

On PurPur 1.18.2.

**Comment by imWillX** [comment]
We had an update with a breaking change. 

Update hex to {#111111} from #111111`. This can be fixed using a regex replace.
