### ISSUE TITLE
Animated Lores, and Crate Name Holograms

### ISSUE THREAD

**Issue by xXSKILLS2015Xx** [Hazebyte/CrateReloaded#84]
I have a feature request/suggestion for adding the option to give hologram crate names animated color. (Cycles through all colors in Minecraft color code). Also The option to give items multiple lore lines and being able to give items animated names and lores too. If this can also be added to items displayed in the crate that would be amazing. That's all the request I have for you today, thank you.

~Tap

**Comment by imWillX** [comment]
Hologram should have a rainbow color &u.
