### ISSUE TITLE
Crate set on a skull block stops working after the first use.

### ISSUE THREAD

**Issue by mibby** [Hazebyte/CrateReloaded#88]
CrateReloaded build 1.3.80

I set a crate location on a skull block. (The skull is a skin of a chest to simulate a small chest.) It is floating one block above a slab piece. When you use a crate key on the crate, it works the first time but then stops entirely. You are still able to right click the chest and be knocked back (including it saying you don't have a key when holding a key in your hand). 

Setting the skull block to a normal chest, chests can be opened again. Perhaps may have something to do with chest open/close animation?
![link](http://i.imgur.com/G4Xno9k.png)

**Comment by imWillX** [comment]
Hey Mibby,

What is type of item are you using for the key? We're handling the events via interactions and some materials don't work well.

Can you try setting your key to a certain block? ex: Diamond Block.

**Comment by mibby** [comment]
I keep the key item to a tripwire hook. The crate in this example was a specific skinned skull head. It broke after trying to use it a couple of times presumably because there is no open/close animation or that it is not a solid 1x1 block size. I have not tested using a crate on other solid blocks but all chest variants (ender, normal, locked, shulker box) seem to work fine.

**Comment by imWillX** [comment]
Sorry, I have to rephrase that. Can you set your key item to a block. ie instead of tripwire, use a block.

**Comment by imWillX** [comment]
@mibby Bump!

**Comment by mibby** [comment]
@imWillX My apologies! I've been extremely busy with work. 

It seems you can no longer right click a tripwire key item on a chest that is defined on a skull block. Only when you are in creative with creative-control enabled can you right click the skull block chest location with your hand (or any random item in your inventory) for it to use a key somewhere in your inventory. 

Note: I personally think you should be forced to right click with the key in your hand, even in creative, but I understand it could be a nuisance for players to have to enter survival to move the key to their hotbar. Just odd that you could right click a chest if you were in creative and accidentally use up your key if you didn't know you had one on you.

Right clicking the skull block with a solid block key item does seem to work. You just need to be greater than 1 block distance away from it due to 'placing' the block in front of the chest.

**Comment by imWillX** [comment]
It appears anything with redstone-like type doesn't trigger a hand event -- only an offhand event.

I updated my method to support offhand for the following items: redstone, lever, plates, buttons, tripwire hook. [1.12] `alpha4`
