### ISSUE TITLE
Sponge Port

### ISSUE THREAD

**Issue by runescapejon** [Hazebyte/CrateReloaded#95]
Hello can you port over to Sponge Api ?
Link: https://www.spongepowered.org/

Thanks

**Comment by imWillX** [comment]
updated title.

**Comment by imWillX** [comment]
@runescapejon interested but no time. I hope you found a crate plugin for Sponge.

**Comment by runescapejon** [comment]
over the past few years they are some great crates plugins on sponge they even offer a web base for configuration your crate instead of using only either yml/json/hocon on top of that they much to offer from other crates and Sponge API <3 as well sorry

**Comment by imWillX** [comment]
@runescapejon I agree -- the plugins on sponge look pretty cool :)
